GO
/****** Object:  StoredProcedure [USERFIELDS].[ma_usp_magic_botypes_dml]    Script Date: 08/06/2021 10:25:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER proc [USERFIELDS].[ma_usp_magic_botypes_dml] ( @xmlInput as xml, @PKValueOut as varchar(50) output, @msg as varchar(4000) output, @errId int output )
as
/*******************************************************************************
   ** Version: 1.0
   ** Name: ma_usp_magic_botypes_dml	
   ** Schema: USERFIELDS
   ** Desc:   The procedure is automatically generated by the engine
   **
   ** Table:   
   **
   ** Auth:	the Engine
   ** Date: 14/09/2016
   *******************************************************************************
   ** Change History
   *******************************************************************************
   ** Date:               Author:         Description:
   ** 14/09/2016		  Dario
   ** 08/06/2021          Dario			 added unescape due to XSS prevention on XML cols 
**********************************************************************************/
Declare @actionType as varchar(50) = @xmlInput.value('(/SQLP/ACTION/@TYPE)[1]','varchar(50)');
Declare @arevisId as int = @xmlInput.value('(/SQLP/SESSIONVARS/@idbusinessunit)[1]','int');
Declare @rootDirTmpUploads as varchar(500) = @xmlInput.value('(/SQLP/SESSIONVARS/@Rootdirforupload)[1]','varchar(500)');
Declare @rootDirUploads as varchar(500) = @xmlInput.value('(/SQLP/SESSIONVARS/@Rootdirforcustomer)[1]','varchar(500)');
Declare @userId as int = @xmlInput.value('(/SQLP/SESSIONVARS/@iduser)[1]','int');
declare @ID as int = @xmlInput.value('(/SQLP/P/@ID)[1]', 'int');
declare @BusinessObjectType as nvarchar(50) = @xmlInput.value('(/SQLP/P/@BusinessObjectType)[1]', 'nvarchar(50)');
declare @Description as varchar(512) = @xmlInput.value('(/SQLP/P/@Description)[1]', 'varchar(512)');
declare @EntityName as nvarchar(128) = dbo.uf_replace_to_null(@xmlInput.value('(/SQLP/P/@EntityName)[1]', 'nvarchar(128)'));
declare @UserColumns_ID as int = dbo.uf_replace_to_null(@xmlInput.value('(/SQLP/P/@UserColumns_ID)[1]', 'int'));
declare @ColumnsDefinition as nvarchar(max) = dbo.uf_replace_to_null(@xmlInput.value('(/SQLP/P/@ColumnsDefinition)[1]', 'nvarchar(max)'));
DECLARE @GridExtension AS nvarchar(max) = dbo.uf_replace_to_null(@xmlInput.value('(/SQLP/P/@GridExtension)[1]', 'nvarchar(max)'));
declare @ColumnsDefinitionXML as nvarchar(max) = dbo.uf_replace_to_null([dbo].[Magic_Unescape_XML](@xmlInput.value('(/SQLP/P/@ColumnsDefinitionXML)[1]', 'nvarchar(max)')));
declare @DeveloperColumnsDefinition as nvarchar(max) = dbo.uf_replace_to_null(@xmlInput.value('(/SQLP/P/@DeveloperColumnsDefinition)[1]', 'nvarchar(max)'));
DECLARE @DeveloperGridExtension AS nvarchar(max) = dbo.uf_replace_to_null(@xmlInput.value('(/SQLP/P/@DeveloperGridExtension)[1]', 'nvarchar(max)'));
declare @DeveloperColumnsDefinitionXML as nvarchar(max) = dbo.uf_replace_to_null([dbo].[Magic_Unescape_XML](@xmlInput.value('(/SQLP/P/@DeveloperColumnsDefinitionXML)[1]', 'nvarchar(max)')));

select @ColumnsDefinitionXML

DECLARE @isDeveloper bit =  @xmlInput.value('(/SQLP/P/@isDeveloperFunction)[1]','bit');

-- Business Logic Script
begin tran
begin try
if NOT EXISTS(SELECT * FROM USERFIELDS.Magic_UserColumns muc WHERE muc.BOType_ID = @ID)
begin

	insert into USERFIELDS.Magic_UserColumns
	(
		BOType_ID,
		ColumnsDefinition,
		GridExtension,
		ColumnsDefinitionXML,
		[DeveloperColumnsDefinition],
		[DeveloperGridExtension],
		[DeveloperColumnsDefinitionXML]

	)
	values
	(
		@ID,
		@ColumnsDefinition,
		@GridExtension,
		@ColumnsDefinitionXML,
		@DeveloperColumnsDefinition,
		@DeveloperGridExtension,
		@DeveloperColumnsDefinitionXML

	)
	set @PKValueOut = cast(scope_identity() as varchar(13));
	SET @UserColumns_ID = @PKValueOut
end
else 
BEGIN

	IF (@isDeveloper=1)
			update USERFIELDS.Magic_UserColumns
			SET
			[DeveloperColumnsDefinition] = @DeveloperColumnsDefinition,
				[DeveloperGridExtension] = @DeveloperGridExtension,
				[DeveloperColumnsDefinitionXML] = @DeveloperColumnsDefinitionXML,
				DeveloperColumnsModifiedBy = @userId
			where ID = @UserColumns_ID;
		ELSE
			update USERFIELDS.Magic_UserColumns
			set
				ColumnsDefinition = @ColumnsDefinition,
				GridExtension = @GridExtension,
				ColumnsDefinitionXML =@ColumnsDefinitionXML,
				UserColumnsModifiedBy = @userId
			where ID = @UserColumns_ID;
end;
--manage the user trace for the last operation
IF (@isDeveloper = 1)
	UPDATE  USERFIELDS.Magic_UserColumns
	SET DeveloperColumnsModifiedBy = @userId
	WHERE ID = @UserColumns_ID
ELSE
	UPDATE  USERFIELDS.Magic_UserColumns
	SET UserColumnsModifiedBy = @userId
	WHERE ID = @UserColumns_ID


--details management
DECLARE @xml XML --= CONVERT(xml,@ColumnsDefinitionXML)
DECLARE @xmldev XML --= CONVERT(xml,@ColumnsDefinitionXML)
SET @xmldev = (SELECT DeveloperColumnsDefinitionXML FROM  USERFIELDS.Magic_UserColumns WHERE ID=@UserColumns_ID)
set @xml = (SELECT ColumnsDefinitionXML  FROM  USERFIELDS.Magic_UserColumns WHERE ID=@UserColumns_ID)

DECLARE @currentd TABLE (
[Magic_UserColumns_ID] int,
columnName nvarchar(100),
JSONLabels nvarchar(max),
[Required] bit DEFAULT (0),
UserColumnDataType_ID int , 
VirtualTableID int null,
Orderby int ,
VisibleAsColumn bit DEFAULT(0),
SearchGridMagicGridName nvarchar(200),
SearchGridLabelColumn nvarchar(200),
SearchGridValueColumn nvarchar(200),
[BOTypeGridUserTab_ID] int
)


INSERT INTO @currentd
SELECT @UserColumns_ID AS [Magic_UserColumns_ID],
	   t.p.value('(name)[1]','nvarchar(100)') AS  columnName,
	   t.p.value('(labels)[1]','nvarchar(max)') AS JSONLabels,
	   t.p.value('(required)[1]','bit') AS Required,
	   t.p.value('(type)[1]','int') AS UserColumnDataType_ID,
	   muvt.ID AS VirtualTableID,
	   t.p.value('(Order)[1]','int') AS Orderby,
	   t.p.value('(visibleAsColumn)[1]','bit') AS VisibleAsColumn,
	  -- t.p.value('(searchGridMagicGridName)[1]','nvarchar(200)') AS SearchGridMagicGridName,
	  -- t.p.value('(searchGridLabelColumn)[1]','nvarchar(200)') AS SearchGridLabelColumn,
	 --  t.p.value('(searchGridValueColumn)[1]','nvarchar(200)') AS searchGridValueColumn,
	   CASE isnull(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'') 
				when '' then null 
				else dbo.Magic_GetValueFromJsonField(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'searchGridMagicGridName') end AS SearchGridMagicGridName,
	    CASE isnull(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'') 
				when '' then NULL
				ELSE  dbo.Magic_GetValueFromJsonField(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'searchGridLabelColumn') end AS SearchGridLabelColumn,
	      CASE isnull(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'') 
			when '' then null else 
			dbo.Magic_GetValueFromJsonField(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'searchGridValueColumn') end AS searchGridValueColumn,
	   t.p.value('(tab)[1]','int') AS [BOTypeGridUserTab_ID]
	   FROM @xml.nodes('/rows/row') t(p)
	   LEFT JOIN USERFIELDS.Magic_UserVirtualTables muvt 
	   ON dbo.uf_replace_to_null(t.p.value('(virtualTable)[1]','nvarchar(100)'))  = muvt.Code 
	   UNION
SELECT @UserColumns_ID AS [Magic_UserColumns_ID],
	   t.p.value('(name)[1]','nvarchar(100)') AS  columnName,
	   t.p.value('(labels)[1]','nvarchar(max)') AS JSONLabels,
	   t.p.value('(required)[1]','bit') AS Required,
	   t.p.value('(type)[1]','int') AS UserColumnDataType_ID,
	   muvt.ID AS VirtualTableID,
	   t.p.value('(Order)[1]','int') AS Orderby,
	   t.p.value('(visibleAsColumn)[1]','bit') AS VisibleAsColumn,
	--  t.p.value('(searchGridMagicGridName)[1]','nvarchar(200)') AS SearchGridMagicGridName,
	--   t.p.value('(searchGridLabelColumn)[1]','nvarchar(200)') AS SearchGridLabelColumn,
	--   t.p.value('(searchGridValueColumn)[1]','nvarchar(200)') AS searchGridValueColumn,
	   CASE isnull(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'') 
				when '' then null 
				else dbo.Magic_GetValueFromJsonField(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'searchGridMagicGridName') end AS SearchGridMagicGridName,
	    CASE isnull(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'') 
				when '' then NULL
				ELSE  dbo.Magic_GetValueFromJsonField(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'searchGridLabelColumn') end AS SearchGridLabelColumn,
	      CASE isnull(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'') 
			when '' then null else 
			dbo.Magic_GetValueFromJsonField(t.p.value('(searchGrid)[1]','nvarchar(1000)'),'searchGridValueColumn') end AS searchGridValueColumn,
	   t.p.value('(tab)[1]','int') AS [BOTypeGridUserTab_ID]
	   FROM @xmldev.nodes('/rows/row') t(p)
	   LEFT JOIN USERFIELDS.Magic_UserVirtualTables muvt 
	   ON dbo.uf_replace_to_null(t.p.value('(virtualTable)[1]','nvarchar(100)'))  = muvt.Code 
	

DELETE FROM [USERFIELDS].[Magic_UserColumnsDetails] WHERE [Magic_UserColumns_ID] = @UserColumns_ID AND [ColumnName] NOT IN 
(SELECT 
ColumnName from @currentd)

UPDATE cd
SET cd.ColumnLabels = c.JSONLabels,
	cd.Required = c.Required,
	cd.DataType_ID = c.UserColumnDataType_ID,
	cd.VirtualTable_ID = c.VirtualTableID,
	iOrder = c.Orderby,
	cd.VisibleAsColumn = c.VisibleAsColumn,
	cd.SearchGridMagicGridName = [dbo].[uf_replace_to_null](c.SearchGridMagicGridName),
	cd.SearchGridLabelColumn = [dbo].[uf_replace_to_null](c.SearchGridLabelColumn),
	cd.SearchGridValueColumn = [dbo].[uf_replace_to_null](c.searchGridValueColumn), 
	cd.[BOTypeGridUserTab_ID] = CASE c.[BOTypeGridUserTab_ID] WHEN 0 THEN NULL ELSE c.[BOTypeGridUserTab_ID] end
FROM [USERFIELDS].[Magic_UserColumnsDetails] cd
INNER JOIN @currentd c
ON c.columnName = cd.ColumnName
WHERE cd.[Magic_UserColumns_ID] = @UserColumns_ID


INSERT INTO [USERFIELDS].[Magic_UserColumnsDetails]
([Magic_UserColumns_ID],
[ColumnName],
[ColumnLabels],
[Required],
[DataType_ID],
[VirtualTable_ID],
iOrder,
VisibleAsColumn,
CreatedByDeveloper,
SearchGridMagicGridName,
SearchGridLabelColumn,
SearchGridValueColumn,
[BOTypeGridUserTab_ID])
SELECT c.[Magic_UserColumns_ID],
c.[ColumnName],
c.JSONLabels,
c.[Required],
c.UserColumnDataType_ID,
c.VirtualTableID,
c.Orderby,
c.VisibleAsColumn,
@isDeveloper,
[dbo].[uf_replace_to_null](c.SearchGridMagicGridName) ,
[dbo].[uf_replace_to_null](c.searchGridLabelColumn),
[dbo].[uf_replace_to_null](c.SearchGridValueColumn),
CASE c.[BOTypeGridUserTab_ID] WHEN 0 THEN NULL ELSE c.[BOTypeGridUserTab_ID] end
 FROM @currentd c
 LEFT JOIN USERFIELDS.Magic_UserColumnsDetails mucd
 ON c.Magic_UserColumns_ID = mucd.Magic_UserColumns_ID AND mucd.ColumnName = c.columnName
 WHERE mucd.ID IS null



commit tran
select @errId = 0, @msg = dbo.uf_ret_msg_content(@userId,'0');
end try
begin catch
set @msg = error_message();
select @errId = 200001, @msg = '{"type":"ERR","content":"' + @msg + '"}'
rollback tran
end catch


