//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_FTP_Settings
    {
        public int ID { get; set; }
        public int Server { get; set; }
        public string Local_Path { get; set; }
        public string Remote_Path { get; set; }
        public int Transfer_Type { get; set; }
        public string Code { get; set; }
        public bool ExtractArchiveFiles { get; set; }
        public bool DeleteFiles { get; set; }
    
        public virtual Magic_FTP_Servers Magic_FTP_Servers { get; set; }
        public virtual Magic_FTP_Transfer_Types Magic_FTP_Transfer_Types { get; set; }
    }
}
