//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_Eve_ScriptType
    {
        public Magic_Eve_ScriptType()
        {
            this.Magic_Eve_Event = new HashSet<Magic_Eve_Event>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Magic_Eve_Event> Magic_Eve_Event { get; set; }
    }
}
