//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_Eve_Event
    {
        public Magic_Eve_Event()
        {
            this.Magic_Eve_Event1 = new HashSet<Magic_Eve_Event>();
            this.Magic_Eve_PlannedEvent = new HashSet<Magic_Eve_PlannedEvent>();
        }
    
        public int EventID { get; set; }
        public int EventActionID { get; set; }
        public int EventScriptTypeID { get; set; }
        public string Description { get; set; }
        public string ScriptName { get; set; }
        public Nullable<int> SystemMessageID { get; set; }
        public Nullable<int> ChildEventID { get; set; }
    
        public virtual Magic_Eve_ActionType Magic_Eve_ActionType { get; set; }
        public virtual ICollection<Magic_Eve_Event> Magic_Eve_Event1 { get; set; }
        public virtual Magic_Eve_Event Magic_Eve_Event2 { get; set; }
        public virtual Magic_Eve_ScriptType Magic_Eve_ScriptType { get; set; }
        public virtual ICollection<Magic_Eve_PlannedEvent> Magic_Eve_PlannedEvent { get; set; }
    }
}
