//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_FTP_Servers
    {
        public Magic_FTP_Servers()
        {
            this.Magic_FTP_Settings = new HashSet<Magic_FTP_Settings>();
        }
    
        public int ID { get; set; }
        public int Protocol { get; set; }
        public Nullable<int> Ftp_Encryption { get; set; }
        public string Host_Name { get; set; }
        public int Port_Number { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Timeout { get; set; }
        public bool Is_Passive { get; set; }
        public string Private_Key_Passphrase { get; set; }
        public string Ssh_Host_Key_Fingerprint { get; set; }
        public string Ssh_Private_Key_Path { get; set; }
        public string Tls_Host_Certificate_Fingerprint { get; set; }
        public string Tls_Client_Certificate_Path { get; set; }
        public string Webdav_Root { get; set; }
    
        public virtual Magic_FTP_Encryptions Magic_FTP_Encryptions { get; set; }
        public virtual Magic_FTP_Protocols Magic_FTP_Protocols { get; set; }
        public virtual ICollection<Magic_FTP_Settings> Magic_FTP_Settings { get; set; }
    }
}
