//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_FTP_Transfer_Types
    {
        public Magic_FTP_Transfer_Types()
        {
            this.Magic_FTP_Settings = new HashSet<Magic_FTP_Settings>();
        }
    
        public int ID { get; set; }
        public bool Is_Upload { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Magic_FTP_Settings> Magic_FTP_Settings { get; set; }
    }
}
