//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_FTP_Encryptions
    {
        public Magic_FTP_Encryptions()
        {
            this.Magic_FTP_Servers = new HashSet<Magic_FTP_Servers>();
        }
    
        public int ID { get; set; }
        public int Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Magic_FTP_Servers> Magic_FTP_Servers { get; set; }
    }
}
