//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_Eve_Track
    {
        public int TrackID { get; set; }
        public Nullable<int> PlannedEventID { get; set; }
        public Nullable<System.DateTime> tsExecutionStart { get; set; }
        public Nullable<System.DateTime> tsExecutionEnd { get; set; }
        public string AlertMessage { get; set; }
        public string DbMessage { get; set; }
    
        public virtual Magic_Eve_PlannedEvent Magic_Eve_PlannedEvent { get; set; }
    }
}
