//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_Eve_PlannedEvent
    {
        public Magic_Eve_PlannedEvent()
        {
            this.Magic_Eve_Track = new HashSet<Magic_Eve_Track>();
        }
    
        public int IDPlannedEvent { get; set; }
        public int EventID { get; set; }
        public Nullable<int> IntervalID { get; set; }
        public System.DateTime tsStartExecution { get; set; }
        public Nullable<System.DateTime> tsNextExecution { get; set; }
        public Nullable<System.DateTime> tsLastExecution { get; set; }
        public bool Active { get; set; }
        public string LastExecutionMessage { get; set; }
    
        public virtual Magic_Eve_Interval Magic_Eve_Interval { get; set; }
        public virtual ICollection<Magic_Eve_Track> Magic_Eve_Track { get; set; }
        public virtual Magic_Eve_Event Magic_Eve_Event { get; set; }
    }
}
