//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagicDBEntities : DbContext
    {
        public MagicDBEntities()
            : base("name=MagicDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Magic_Eve_ActionType> Magic_Eve_ActionType { get; set; }
        public virtual DbSet<Magic_Eve_Interval> Magic_Eve_Interval { get; set; }
        public virtual DbSet<Magic_Eve_ScriptType> Magic_Eve_ScriptType { get; set; }
        public virtual DbSet<Magic_Eve_Track> Magic_Eve_Track { get; set; }
        public virtual DbSet<Magic_Eve_PlannedEvent> Magic_Eve_PlannedEvent { get; set; }
        public virtual DbSet<Magic_Eve_Event> Magic_Eve_Event { get; set; }
        public virtual DbSet<Magic_FTP_Protocols> Magic_FTP_Protocols { get; set; }
        public virtual DbSet<Magic_FTP_Transfer_Types> Magic_FTP_Transfer_Types { get; set; }
        public virtual DbSet<Magic_FTP_Encryptions> Magic_FTP_Encryptions { get; set; }
        public virtual DbSet<Magic_FTP_Servers> Magic_FTP_Servers { get; set; }
        public virtual DbSet<Magic_FTP_Settings> Magic_FTP_Settings { get; set; }
    }
}
