//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicEventsManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_Eve_Interval
    {
        public Magic_Eve_Interval()
        {
            this.Magic_Eve_PlannedEvent = new HashSet<Magic_Eve_PlannedEvent>();
        }
    
        public int IntervalID { get; set; }
        public string Description { get; set; }
        public Nullable<int> IntervalinSeconds { get; set; }
        public string DayofWeek { get; set; }
        public string Month { get; set; }
    
        public virtual ICollection<Magic_Eve_PlannedEvent> Magic_Eve_PlannedEvent { get; set; }
    }
}
