/*! 
* DevExtreme Web
* Version: 16.1.4
* Build date: Jun 22, 2016
*
* Copyright (c) 2012 - 2016 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

(function(root, factory) {
    factory(DevExpress.localization.message)
}(this, function(message) {
    message.load({
        "it": {
            "Yes": "Si",
            "No": "No",
            "Cancel": "Cancel",
            "Clear": "Clear",
            "Done": "Fatto",
            "Loading": "Loading...",
            "Select": "Seleziona...",
            "Search": "Cerca",
            "Back": "Indietro",
            "OK": "OK",
            "dxCollectionWidget-noDataText": "Non ci sono dati",
            "validation-required": "Obbligatorio",
            "validation-required-formatted": "{0} obblifatorio",
            "validation-numeric": "Il valore deve essere un numero",
            "validation-numeric-formatted": "{0} deve essere un numero",
            "validation-range": "Valore fuori range",
            "validation-range-formatted": "{0} fuori range",
            "validation-stringLength": "Lunghezza del valore non corretta",
            "validation-stringLength-formatted": "Lunghezza di {0} non corretta",
            "validation-custom": "Valore non valido",
            "validation-custom-formatted": "{0} non valido",
            "validation-compare": "I valori non corrispondono",
            "validation-compare-formatted": "{0} non corrisponde",
            "validation-pattern": "Il valore non corrisponde al pattern",
            "validation-pattern-formatted": "{0} non corrisponde al pattern",
            "validation-email": "Email non valida",
            "validation-email-formatted": "{0} non valido",
            "validation-mask": "Valore non valido",
            "dxLookup-searchPlaceholder": "Min numero di caratteri: {0}",
            "dxList-pullingDownText": "Scorri giù per aggiornare...",
            "dxList-pulledDownText": "Rilascia per aggiornare...",
            "dxList-refreshingText": "Refreshing...",
            "dxList-pageLoadingText": "Loading...",
            "dxList-nextButtonText": "Altro",
            "dxList-selectAll": "Seleziona Tutto",
            "dxListEditDecorator-delete": "Elimina",
            "dxListEditDecorator-more": "Altro",
            "dxScrollView-pullingDownText": "Scorri giù per aggiornare...",
            "dxScrollView-pulledDownText": "Rilascia per aggiornare...",
            "dxScrollView-refreshingText": "Refreshing...",
            "dxScrollView-reachBottomText": "Loading...",
            "dxDateBox-simulatedDataPickerTitleTime": "Seleziona orario",
            "dxDateBox-simulatedDataPickerTitleDate": "Seleziona data",
            "dxDateBox-simulatedDataPickerTitleDateTime": "Seleziona data e orario",
            "dxDateBox-validation-datetime": "Il valore deve essere una data o un orario",
            "dxFileUploader-selectFile": "Scegli file",
            "dxFileUploader-dropFile": "o Trascinalo qui",
            "dxFileUploader-bytes": "bytes",
            "dxFileUploader-kb": "kb",
            "dxFileUploader-Mb": "Mb",
            "dxFileUploader-Gb": "Gb",
            "dxFileUploader-upload": "Upload",
            "dxFileUploader-uploaded": "Caricato",
            "dxFileUploader-readyToUpload": "Pronto per upload",
            "dxFileUploader-uploadFailedMessage": "Upload fallito",
            "dxRangeSlider-ariaFrom": "Da",
            "dxRangeSlider-ariaTill": "A",
            "dxSwitch-onText": "ON",
            "dxSwitch-offText": "OFF",
            "dxForm-optionalMark": "facolativo",
            "dxForm-requiredMessage": "{0} obbligatorio",
            "dxNumberBox-invalidValueMessage": "Il Valore deve essere un numero",
            "dxDataGrid-columnChooserTitle": "Selettore Colonne",
            "dxDataGrid-columnChooserEmptyText": "Trascina una colonna qui per nasconderla",
            "dxDataGrid-groupContinuesMessage": "Continua nella prossima paggina",
            "dxDataGrid-groupContinuedMessage": "Continua dalla pagina precedente",
            "dxDataGrid-groupHeaderText": "Ragguppa per Questa Colonna",
            "dxDataGrid-ungroupHeaderText": "Separa",
            "dxDataGrid-ungroupAllText": "Separa Tutto",
            "dxDataGrid-editingEditRow": "Modifica",
            "dxDataGrid-editingSaveRowChanges": "Salva",
            "dxDataGrid-editingCancelRowChanges": "Annulla",
            "dxDataGrid-editingDeleteRow": "Elimina",
            "dxDataGrid-editingUndeleteRow": "Ripristina",
            "dxDataGrid-editingConfirmDeleteMessage": "Confermmi eliminazione di questo record?",
            "dxDataGrid-validationCancelChanges": "Annullare le modifiche",
            "dxDataGrid-groupPanelEmptyText": "Trascina una testata colonna qui per raggruppare per quella colonna",
            "dxDataGrid-noDataText": "Nessun dato",
            "dxDataGrid-searchPanelPlaceholder": "Cerca...",
            "dxDataGrid-filterRowShowAllText": "(Tutto)",
            "dxDataGrid-filterRowResetOperationText": "Reset",
            "dxDataGrid-filterRowOperationEquals": "Uguale",
            "dxDataGrid-filterRowOperationNotEquals": "Diverso",
            "dxDataGrid-filterRowOperationLess": "Minore di",
            "dxDataGrid-filterRowOperationLessOrEquals": "Minore o uguale a",
            "dxDataGrid-filterRowOperationGreater": "Maggiore di",
            "dxDataGrid-filterRowOperationGreaterOrEquals": "Maggiore o uguale a",
            "dxDataGrid-filterRowOperationStartsWith": "Inizia con",
            "dxDataGrid-filterRowOperationContains": "Contiene",
            "dxDataGrid-filterRowOperationNotContains": "Non contiene",
            "dxDataGrid-filterRowOperationEndsWith": "Termina con",
            "dxDataGrid-filterRowOperationBetween": "Tra",
            "dxDataGrid-filterRowOperationBetweenStartText": "Inizio",
            "dxDataGrid-filterRowOperationBetweenEndText": "Fine",
            "dxDataGrid-applyFilterText": "Applica Filtro",
            "dxDataGrid-trueText": "vero",
            "dxDataGrid-falseText": "falso",
            "dxDataGrid-sortingAscendingText": "Ordinamento Crescente",
            "dxDataGrid-sortingDescendingText": "Ordinamento Decrescente",
            "dxDataGrid-sortingClearText": "Azzera Ordinamento",
            "dxDataGrid-editingSaveAllChanges": "Salva modifiche",
            "dxDataGrid-editingCancelAllChanges": "Abbandona modifiche",
            "dxDataGrid-editingAddRow": "Aggiungi una riga",
            "dxDataGrid-summaryMin": "Min: {0}",
            "dxDataGrid-summaryMinOtherColumn": "Min di {1} : {0}",
            "dxDataGrid-summaryMax": "Max: {0}",
            "dxDataGrid-summaryMaxOtherColumn": "Max di {1} : {0}",
            "dxDataGrid-summaryAvg": "Media: {0}",
            "dxDataGrid-summaryAvgOtherColumn": "Media di {1} : {0}",
            "dxDataGrid-summarySum": "Somma: {0}",
            "dxDataGrid-summarySumOtherColumn": "Somma di {1} : {0}",
            "dxDataGrid-summaryCount": "Conteggio: {0}",
            "dxDataGrid-columnFixingFix": "Fissa",
            "dxDataGrid-columnFixingUnfix": "Slega",
            "dxDataGrid-columnFixingLeftPosition": "A sinistra",
            "dxDataGrid-columnFixingRightPosition": "A destra",
            "dxDataGrid-exportTo": "Esporta",
            "dxDataGrid-exportToExcel": "Esporta (file Excel)",
            "dxDataGrid-excelFormat": "File Excel",
            "dxDataGrid-selectedRows": "Righe selezionate",
            "dxDataGrid-exportSelectedRows": "Esporta le righe selezionate",
            "dxDataGrid-exportAll": "Esporta tutti i dati",
            "dxDataGrid-headerFilterEmptyValue": "(Blanks)",
            "dxDataGrid-headerFilterOK": "OK",
            "dxDataGrid-headerFilterCancel": "Annulla",
            "dxDataGrid-ariaColumn": "Colonna",
            "dxDataGrid-ariaValue": "Valore",
            "dxDataGrid-ariaFilterCell": "Filter cell",
            "dxDataGrid-ariaCollapse": "Comprimi",
            "dxDataGrid-ariaExpand": "Espandi",
            "dxDataGrid-ariaDataGrid": "Data grid",
            "dxDataGrid-ariaSearchInGrid": "Cerca nella griglia",
            "dxDataGrid-ariaSelectAll": "Seleziona tutto",
            "dxDataGrid-ariaSelectRow": "Seleziona riga",
            "dxPager-infoText": "Pag {0} di {1} ({2} elementi)",
            "dxPager-pagesCountText": "di",
            "dxPivotGrid-grandTotal": "Totale Finale",
            "dxPivotGrid-total": "{0} Totale",
            "dxPivotGrid-fieldChooserTitle": "Selettore Campo",
            "dxPivotGrid-showFieldChooser": "Mostra Selettore Campo",
            "dxPivotGrid-expandAll": "Espandi Tutto",
            "dxPivotGrid-collapseAll": "Comprimi Tutto",
            "dxPivotGrid-sortColumnBySummary": "Ordina \"{0}\" per Questa Colonna",
            "dxPivotGrid-sortRowBySummary": "Ordina \"{0}\" per Questa Colonna",
            "dxPivotGrid-removeAllSorting": "Rimuovi Ordinamenti",
            "dxPivotGrid-rowFields": "Campi Riga",
            "dxPivotGrid-columnFields": "Campi Colonna",
            "dxPivotGrid-dataFields": "Campi Data",
            "dxPivotGrid-filterFields": "Campi Filtro",
            "dxPivotGrid-allFields": "Tutti i Campi",
            "dxPivotGrid-columnFieldArea": "Trascina i Campi Colonna Qui",
            "dxPivotGrid-dataFieldArea": "Trascina i Campi Data Qui",
            "dxPivotGrid-rowFieldArea": "Trascina i Campi Riga Qui",
            "dxPivotGrid-filterFieldArea": "Trascina i Campi Filtro Qui",
            "dxScheduler-editorLabelTitle": "Oggetto",
            "dxScheduler-editorLabelStartDate": "Data Inizio",
            "dxScheduler-editorLabelEndDate": "Data Fine",
            "dxScheduler-editorLabelDescription": "Descrizione",
            "dxScheduler-editorLabelRecurrence": "Ripeti",
            "dxScheduler-openAppointment": "Apri appuntamento",
            "dxScheduler-recurrenceNever": "Mai",
            "dxScheduler-recurrenceDaily": "Giornalmente",
            "dxScheduler-recurrenceWeekly": "Settimanalmente",
            "dxScheduler-recurrenceMonthly": "Mensilmente",
            "dxScheduler-recurrenceYearly": "Annualmente",
            "dxScheduler-recurrenceEvery": "Ogni",
            "dxScheduler-recurrenceEnd": "Fine ripetizione",
            "dxScheduler-recurrenceAfter": "Dopo",
            "dxScheduler-recurrenceOn": "Il",
            "dxScheduler-recurrenceRepeatDaily": "giorno(i)",
            "dxScheduler-recurrenceRepeatWeekly": "settimana(e)",
            "dxScheduler-recurrenceRepeatMonthly": "mese(i)",
            "dxScheduler-recurrenceRepeatYearly": "anno(i)",
            "dxScheduler-switcherDay": "Giorno",
            "dxScheduler-switcherWeek": "Settimana",
            "dxScheduler-switcherWorkWeek": "Settimana lavorativa",
            "dxScheduler-switcherMonth": "Mese",
            "dxScheduler-switcherAgenda": "Agenda",
            "dxScheduler-switcherTimelineDay": "Timeline Giorno",
            "dxScheduler-switcherTimelineWeek": "Timeline Settimana",
            "dxScheduler-switcherTimelineWorkWeek": "Timeline Settimana Lavorativa",
            "dxScheduler-switcherTimelineMonth": "Timeline Mese",
            "dxScheduler-recurrenceRepeatOnDate": "alla data",
            "dxScheduler-recurrenceRepeatCount": "occorrenza(e)",
            "dxScheduler-allDay": "Tutto il giorno",
            "dxScheduler-confirmRecurrenceEditMessage": "Vuoi modificare solo questa appuntamento o tutta la serie?",
            "dxScheduler-confirmRecurrenceDeleteMessage": "Vuoi eliminare solo questo appuntamento o tutta la serie?",
            "dxScheduler-confirmRecurrenceEditSeries": "Modifica serie",
            "dxScheduler-confirmRecurrenceDeleteSeries": "Elimina serie",
            "dxScheduler-confirmRecurrenceEditOccurrence": "Modifica appuntamento",
            "dxScheduler-confirmRecurrenceDeleteOccurrence": "Elimina appuntamento",
            "dxScheduler-noTimezoneTitle": "Nessuna timezone",
            "dxCalendar-todayButtonText": "Oggi",
            "dxCalendar-ariaWidgetName": "Calendario",
            "dxColorView-ariaRed": "Rosso",
            "dxColorView-ariaGreen": "Verde",
            "dxColorView-ariaBlue": "Blu",
            "dxColorView-ariaAlpha": "Trasparente",
            "dxColorView-ariaHex": "Codice colore",
            "vizExport-printingButtonText": "Stampa",
            "vizExport-titleMenuText": "Esportazione/Stampa",
            "vizExport-exportButtonText": "{0} file"
        }
    })
}));
//(function(root, factory) {
//    factory(DevExpress.localization.message)
//}(this, function(message) {
//    message.load({it: {
//        "dxLookup-searchPlaceholder": "Numero minimo di caratteri: {0}", "dxList-pullingDownText": "Premi per aggiornare", "dxList-pulledDownText": "Rilascia per aggiornare", "dxList-refreshingText": "Aggiornamento in corso...", "dxList-pageLoadingText": "In caricamento...", "dxList-nextButtonText": "Altro", "dxList-selectAll": "Seleziona tutto", "dxListEditDecorator-delete": "Cancella", "dxListEditDecorator-more": "Altro", "dxScrollView-pullingDownText": "Premi per aggiornare", "dxScrollView-pulledDownText": "Rilascia per aggiornare", "dxScrollView-refreshingText": "Aggiornamento...", "dxScrollView-reachBottomText": "In caricamento...", "dxDateBox-simulatedDataPickerTitleTime": "Seleziona un' orario", "dxDateBox-simulatedDataPickerTitleDate": "Seleziona una data", "dxDateBox-simulatedDataPickerTitleDateTime": "Seleziona data ed ora", "dxDateBox-validation-datetime": "Il valore deve essere un orario od una data", "dxFileUploader-selectFile": "Selezionare il file", "dxFileUploader-dropFile": "Trascina qui il file", "dxFileUploader-bytes": "Bytes", "dxFileUploader-kb": "kb", "dxFileUploader-Mb": "Mb", "dxFileUploader-Gb": "Gb", "dxFileUploader-upload": "Carica", "dxFileUploader-uploaded": "Caricato", "dxFileUploader-readyToUpload": "Pronto al caricamento", "dxFileUploader-uploadFailedMessage": "Caricamento sul server fallito", "dxRangeSlider-ariaFrom": "Da", "dxRangeSlider-ariaTill": "A", "dxSwitch-onText": "Acceso", "dxSwitch-offText": "Spento", "dxForm-optionalMark": "opzionale", "dxForm-requiredMessage": "{0} è un campo obbligatorio", "dxNumberBox-invalidValueMessage": "Il valore deve essere numerico"
//        }})
//}));
//(function(root, factory) {
//    factory(DevExpress.localization.message)
//}(this, function(message) {
//    message.load({it: {
//            "dxDataGrid-columnChooserTitle": "Selezione colonne", "dxDataGrid-columnChooserEmptyText": "Ziehen Sie Spalten hierhin, um sie zu verstecken", "dxDataGrid-groupContinuesMessage": "Weiter auf der nächsten Seite", "dxDataGrid-groupContinuedMessage": "Weiter von der vorherigen Seite", "dxDataGrid-groupHeaderText": "Nach dieser Spalte gruppieren", "dxDataGrid-ungroupHeaderText": "Gruppierung entfernen", "dxDataGrid-ungroupAllText": "Alle Gruppierungen entfernen", "dxDataGrid-editingEditRow": "Bearbeiten", "dxDataGrid-editingSaveRowChanges": "Speichern", "dxDataGrid-editingCancelRowChanges": "Abbrechen", "dxDataGrid-editingDeleteRow": "Entfernen", "dxDataGrid-editingUndeleteRow": "Wiederherstellen", "dxDataGrid-editingConfirmDeleteMessage": "Sind Sie sicher, dass Sie diesen Datensatz löschen wollen?", "dxDataGrid-validationCancelChanges": "Änderungen verwerfen", "dxDataGrid-groupPanelEmptyText": "Ziehen Sie eine Spalte hierhin, um danach zu gruppieren", "dxDataGrid-noDataText": "Keine Daten", "dxDataGrid-searchPanelPlaceholder": "Suchen...", "dxDataGrid-filterRowShowAllText": "(Alle)", "dxDataGrid-filterRowResetOperationText": "Zurücksetzen", "dxDataGrid-filterRowOperationEquals": "Ist gleich", "dxDataGrid-filterRowOperationNotEquals": "Ist nicht gleich", "dxDataGrid-filterRowOperationLess": "Kleiner als", "dxDataGrid-filterRowOperationLessOrEquals": "Kleiner oder gleich", "dxDataGrid-filterRowOperationGreater": "Größer als", "dxDataGrid-filterRowOperationGreaterOrEquals": "Größer oder gleich", "dxDataGrid-filterRowOperationStartsWith": "Beginnt mit", "dxDataGrid-filterRowOperationContains": "Enthält", "dxDataGrid-filterRowOperationNotContains": "Enthält nicht", "dxDataGrid-filterRowOperationEndsWith": "Endet mit", "dxDataGrid-filterRowOperationBetween": "Zwischen", "dxDataGrid-filterRowOperationBetweenStartText": "Anfang", "dxDataGrid-filterRowOperationBetweenEndText": "Ende", "dxDataGrid-applyFilterText": "Filter anwenden", "dxDataGrid-trueText": "wahr", "dxDataGrid-falseText": "falsch", "dxDataGrid-sortingAscendingText": "Aufsteigend sortieren", "dxDataGrid-sortingDescendingText": "Absteigend sortieren", "dxDataGrid-sortingClearText": "Sortierung aufheben", "dxDataGrid-editingSaveAllChanges": "Änderungen speichern", "dxDataGrid-editingCancelAllChanges": "Änderungen verwerfen", "dxDataGrid-editingAddRow": "Neue Zeile", "dxDataGrid-summaryMin": "Min: {0}", "dxDataGrid-summaryMinOtherColumn": "Minimum von {1} ist {0}", "dxDataGrid-summaryMax": "Max: {0}", "dxDataGrid-summaryMaxOtherColumn": "Maximum von {1} ist {0}", "dxDataGrid-summaryAvg": "Ø: {0}", "dxDataGrid-summaryAvgOtherColumn": "Durchschnitt von {1} ist {0}", "dxDataGrid-summarySum": "Summe: {0}", "dxDataGrid-summarySumOtherColumn": "Summe von {1} ist {0}", "dxDataGrid-summaryCount": "Anzahl: {0}", "dxDataGrid-columnFixingFix": "Fixieren", "dxDataGrid-columnFixingUnfix": "Lösen", "dxDataGrid-columnFixingLeftPosition": "Nach links", "dxDataGrid-columnFixingRightPosition": "Nach rechts", "dxDataGrid-exportTo": "Exportieren", "dxDataGrid-exportToExcel": "Exportieren als Excel-Datei", "dxDataGrid-excelFormat": "Excel-Datei", "dxDataGrid-selectedRows": "Ausgewählte Zeilen", "dxDataGrid-exportAll": "Alle Daten exportieren", "dxDataGrid-exportSelectedRows": "Ausgewählte Zeilen exportieren", "dxDataGrid-headerFilterEmptyValue": "(Leerwerte)", "dxDataGrid-headerFilterOK": "OK", "dxDataGrid-headerFilterCancel": "Abbrechen", "dxDataGrid-ariaColumn": "Spalte", "dxDataGrid-ariaValue": "Wert", "dxDataGrid-ariaFilterCell": "Filterzelle", "dxDataGrid-ariaCollapse": "Zusammesklappen", "dxDataGrid-ariaExpand": "Aufklappen", "dxDataGrid-ariaDataGrid": "Datentabelle", "dxDataGrid-ariaSearchInGrid": "Suchen in der Datentabelle", "dxDataGrid-ariaSelectAll": "Alle auswählen", "dxDataGrid-ariaSelectRow": "Zeile auswählen", "dxPager-infoText": "Seite {0} von {1} ({2} Elemente)", "dxPager-pagesCountText": "von", "dxPivotGrid-grandTotal": "Totale", "dxPivotGrid-total": "{0} Totale", "dxPivotGrid-fieldChooserTitle": "Selezione campi", "dxPivotGrid-showFieldChooser": "Mostra la selezione dei campi", "dxPivotGrid-expandAll": "Espandi tutto", "dxPivotGrid-collapseAll": "Comprimi tutto", "dxPivotGrid-sortColumnBySummary": "\"{0}\" per ordinare per questa colonna", "dxPivotGrid-sortRowBySummary": "\"{0}\" per ordinare per riga", "dxPivotGrid-removeAllSorting": "Rimuovi ordinamenti", "dxPivotGrid-rowFields": "Righe", "dxPivotGrid-columnFields": "Colonne", "dxPivotGrid-dataFields": "Misure", "dxPivotGrid-filterFields": "Filtri", "dxPivotGrid-allFields": "Tutti i campi", "dxPivotGrid-columnFieldArea": "Trascina qui le dimensioni da mettere in colonna", "dxPivotGrid-dataFieldArea": "Trascina qui le misure", "dxPivotGrid-rowFieldArea": "Trascina qui le dimensioni da mettere nelle righe", "dxPivotGrid-filterFieldArea": "Trascina qui i filtri", "dxScheduler-editorLabelTitle": "Betreff", "dxScheduler-editorLabelStartDate": "Anfangszeit", "dxScheduler-editorLabelEndDate": "Endzeit", "dxScheduler-editorLabelDescription": "Beschreibung", "dxScheduler-editorLabelRecurrence": "Wiederholung", "dxScheduler-openAppointment": "Termin öffnen", "dxScheduler-recurrenceNever": "Nie", "dxScheduler-recurrenceDaily": "Täglich", "dxScheduler-recurrenceWeekly": "Wöchentlich", "dxScheduler-recurrenceMonthly": "Monatlich", "dxScheduler-recurrenceYearly": "Jährlich", "dxScheduler-recurrenceEvery": "Alle", "dxScheduler-recurrenceEnd": "Wiederholungsende", "dxScheduler-recurrenceAfter": "Nach", "dxScheduler-recurrenceOn": "Am", "dxScheduler-recurrenceRepeatDaily": "Tag(e)", "dxScheduler-recurrenceRepeatWeekly": "Woche(n)", "dxScheduler-recurrenceRepeatMonthly": "Monat(e)", "dxScheduler-recurrenceRepeatYearly": "Jahr(e)", "dxScheduler-switcherDay": "Tag", "dxScheduler-switcherWeek": "Woche", "dxScheduler-switcherWorkWeek": "Arbeitswoche", "dxScheduler-switcherMonth": "Monat", "dxScheduler-switcherTimelineDay": "Zeitstrahl Tag", "dxScheduler-switcherTimelineWeek": "Zeitstrahl Woche", "dxScheduler-switcherTimelineWorkWeek": "Zeitstrahl Arbeitswoche", "dxScheduler-switcherTimelineMonth": "Zeitstrahl Monat", "dxScheduler-switcherAgenda": "Agenda", "dxScheduler-recurrenceRepeatOnDate": "am Datum", "dxScheduler-recurrenceRepeatCount": "Ereignisse", "dxScheduler-allDay": "Ganztägig", "dxScheduler-confirmRecurrenceEditMessage": "Möchten Sie nur diesen Termin bearbeiten, oder die gesamte Serie?", "dxScheduler-confirmRecurrenceDeleteMessage": "Möchten Sie nur diesen Termin löschen, oder die gesamte Serie?", "dxScheduler-confirmRecurrenceEditSeries": "Serie bearbeiten", "dxScheduler-confirmRecurrenceDeleteSeries": "Serie löschen", "dxScheduler-confirmRecurrenceEditOccurrence": "Termin bearbeiten", "dxScheduler-confirmRecurrenceDeleteOccurrence": "Termin löschen", "dxScheduler-noTimezoneTitle": "Keine Zeitzone", "dxCalendar-todayButtonText": "Heute", "dxCalendar-ariaWidgetName": "Kalendar", "dxColorView-ariaRed": "Rot", "dxColorView-ariaGreen": "Grün", "dxColorView-ariaBlue": "Blau", "dxColorView-ariaAlpha": "Transparenz", "dxColorView-ariaHex": "Farbwert", "vizExport-printingButtonText": "Drucken", "vizExport-titleMenuText": "Export/Druck", "vizExport-exportButtonText": "{0}-Datei"
//        }})
//}));
