//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ASSET_asset
    {
        public AS_ASSET_asset()
        {
            this.AS_ASSET_asset1 = new HashSet<AS_ASSET_asset>();
        }
    
        public int AS_ASSET_ID { get; set; }
        public string AS_ASSET_CODE { get; set; }
        public Nullable<int> AS_ASSET_ID_PADRE { get; set; }
        public string AS_ASSET_DESCRIZIONE { get; set; }
        public Nullable<int> AS_ASSET_LOCATION_ID { get; set; }
        public int AS_ASSET_TIPASS_ID { get; set; }
        public int AS_ASSET_TIPSAS_ID { get; set; }
        public Nullable<int> AS_ASSET_SASSPE_ID { get; set; }
        public Nullable<System.DateTime> AS_ASSET_DATA_INIZIO { get; set; }
        public Nullable<System.DateTime> AS_ASSET_DATA_FINE { get; set; }
        public Nullable<decimal> AS_ASSET_SUPERFICIE { get; set; }
        public string AS_ASSET_CODE_OLD { get; set; }
        public Nullable<int> AS_ASSET_ID_ASSET_ORIGINE { get; set; }
        public string AS_ASSET_XML_CAMASS_VALUES { get; set; }
        public string AS_ASSET_XML_CAMUSE_VALUES { get; set; }
        public string GROUPS_LIST { get; set; }
        public Nullable<int> AS_ASSET_EV_STAGE_ID { get; set; }
        public string AS_ASSET_LONG_DESC { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public string AS_ASSET_THUMBNAIL { get; set; }
    
        public virtual ICollection<AS_ASSET_asset> AS_ASSET_asset1 { get; set; }
        public virtual AS_ASSET_asset AS_ASSET_asset2 { get; set; }
    }
}
