//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_SUBTIP_asset_subtipo
    {
        public int AS_SUBTIP_ID { get; set; }
        public int AS_SUBTIP_TIPASS_ID { get; set; }
        public int AS_SUBTIP_TIPSAS_ID { get; set; }
        public Nullable<int> AS_SUBTIP_ORDINE { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    }
}
