//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_V_LOCATION_locationextended
    {
        public int LOCATION_ID { get; set; }
        public string LOCATION_DESCRIPTION { get; set; }
        public string LOCATION_NUMBER { get; set; }
        public Nullable<int> LOCATION_STREET_ID { get; set; }
        public string LOCATION_DESCRIPTION_LONG { get; set; }
    }
}
