//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CF_FIELDS_DATA_TYPE
    {
        public CF_FIELDS_DATA_TYPE()
        {
            this.DO_DOCFIE_fields_document = new HashSet<DO_DOCFIE_fields_document>();
            this.DO_CAMUSE_fields_document_user = new HashSet<DO_CAMUSE_fields_document_user>();
        }
    
        public int CF_FIELDS_DATA_TYPE_ID { get; set; }
        public string CF_FIELDS_DATA_TYPE_CODE { get; set; }
        public string CF_FIELDS_DATA_TYPE_NAME { get; set; }
        public string CF_FIELDS_DATA_TYPE_DATA_TYPE { get; set; }
        public string CF_FIELDS_DATA_TYPE_DESCRIPTION { get; set; }
        public string DATA_TYPE { get; set; }
        public Nullable<int> CHARACTER_MAXIMUM_LENGTH { get; set; }
        public Nullable<byte> NUMERIC_PRECISION { get; set; }
        public Nullable<short> NUMERIC_PRECISION_RADIX { get; set; }
        public Nullable<short> DATETIME_PRECISION { get; set; }
    
        public virtual ICollection<DO_DOCFIE_fields_document> DO_DOCFIE_fields_document { get; set; }
        public virtual ICollection<DO_CAMUSE_fields_document_user> DO_CAMUSE_fields_document_user { get; set; }
    }
}
