//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_CLADOS_dossier_class
    {
        public DO_CLADOS_dossier_class()
        {
            this.DO_DOSSIE_dossier = new HashSet<DO_DOSSIE_dossier>();
        }
    
        public int DO_CLADOS_ID { get; set; }
        public string DO_CLADOS_CODE { get; set; }
        public string DO_CLADOS_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<DO_DOSSIE_dossier> DO_DOSSIE_dossier { get; set; }
    }
}
