//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_CLASTA_class_status
    {
        public int DO_CLASTA_ID { get; set; }
        public Nullable<int> DO_CLASTA_DO_CLADOC_ID { get; set; }
        public Nullable<int> DO_CLASTA_DO_STADOC_ID { get; set; }
        public bool DO_CLASTA_INITIAL { get; set; }
        public bool DO_CLASTA_FINAL { get; set; }
        public int DO_CLASTA_ORDER { get; set; }
        public bool DO_CLASTA_MONITOR_VISIBLE { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual DO_STADOC_status DO_STADOC_status { get; set; }
        public virtual DO_CLADOC_document_class DO_CLADOC_document_class { get; set; }
    }
}
