//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_CLADOC_document_class
    {
        public DO_CLADOC_document_class()
        {
            this.DO_CLASTA_class_status = new HashSet<DO_CLASTA_class_status>();
            this.DO_CLAUTE_class_document_user = new HashSet<DO_CLAUTE_class_document_user>();
            this.DO_TIPDOC_document_type = new HashSet<DO_TIPDOC_document_type>();
            this.DO_CAMUSE_fields_document_user = new HashSet<DO_CAMUSE_fields_document_user>();
            this.DO_DOCFIE_fields_document = new HashSet<DO_DOCFIE_fields_document>();
        }
    
        public int DO_CLADOC_ID { get; set; }
        public string DO_CLADOC_CODE { get; set; }
        public string DO_CLADOC_DESCRIPTION { get; set; }
        public Nullable<bool> DO_CLADOC_FLAG_PHOTO { get; set; }
        public Nullable<int> DO_CLADOC_ORDER { get; set; }
        public string DO_CLADOC_PATH { get; set; }
        public string DO_CLADOC_COLOR { get; set; }
        public Nullable<int> MagicBOLayer_ID { get; set; }
        public Nullable<System.Guid> guidIdentifier { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<DO_CLASTA_class_status> DO_CLASTA_class_status { get; set; }
        public virtual ICollection<DO_CLAUTE_class_document_user> DO_CLAUTE_class_document_user { get; set; }
        public virtual ICollection<DO_TIPDOC_document_type> DO_TIPDOC_document_type { get; set; }
        public virtual ICollection<DO_CAMUSE_fields_document_user> DO_CAMUSE_fields_document_user { get; set; }
        public virtual ICollection<DO_DOCFIE_fields_document> DO_DOCFIE_fields_document { get; set; }
    }
}
