//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_DOCUME_documents
    {
        public DO_DOCUME_documents()
        {
            this.DO_DOCFIL_document_file = new HashSet<DO_DOCFIL_document_file>();
            this.DO_DOCGRO_Document_groups = new HashSet<DO_DOCGRO_Document_groups>();
            this.DO_DOCREL_document_relation = new HashSet<DO_DOCREL_document_relation>();
            this.DO_DOCUME_documents1 = new HashSet<DO_DOCUME_documents>();
        }
    
        public int DO_DOCUME_ID { get; set; }
        public int DO_DOCUME_DO_TIPDOC_ID { get; set; }
        public string DO_DOCUME_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_EXPIRY_DATE { get; set; }
        public int DO_DOCUME_DO_STADOC_ID { get; set; }
        public bool DO_DOCUME_FLAG_NO_ACTIVE { get; set; }
        public string DO_DOCUME_XML_CAMASS_VALUES { get; set; }
        public string DO_DOCUME_XML_CAMUTE_VALUES { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_DATA_PROT { get; set; }
        public string DO_DOCUME_NUM_PROT { get; set; }
        public string DO_DOCUME_NOTE { get; set; }
        public string DO_DOCUME_NUM { get; set; }
        public string DO_DOCUME_CODE { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_DATE_INS { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_DATE_LAS_UPD { get; set; }
        public Nullable<int> DO_DOCUME_USERID { get; set; }
        public Nullable<int> DO_DOCUME_ID_PADRE { get; set; }
        public string GROUPS_LIST { get; set; }
        public bool DO_DOCUME_FL_PRIVAT { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<DO_DOCFIL_document_file> DO_DOCFIL_document_file { get; set; }
        public virtual ICollection<DO_DOCGRO_Document_groups> DO_DOCGRO_Document_groups { get; set; }
        public virtual ICollection<DO_DOCREL_document_relation> DO_DOCREL_document_relation { get; set; }
        public virtual ICollection<DO_DOCUME_documents> DO_DOCUME_documents1 { get; set; }
        public virtual DO_DOCUME_documents DO_DOCUME_documents2 { get; set; }
        public virtual DO_DOCUME_documents DO_DOCUME_documents11 { get; set; }
        public virtual DO_DOCUME_documents DO_DOCUME_documents3 { get; set; }
        public virtual DO_STADOC_status DO_STADOC_status { get; set; }
        public virtual DO_TIPDOC_document_type DO_TIPDOC_document_type { get; set; }
    }
}
