//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_DOSSIE_dossier
    {
        public DO_DOSSIE_dossier()
        {
            this.DO_DOSTIP_dosssier_type_document = new HashSet<DO_DOSTIP_dosssier_type_document>();
            this.DO_DOSUTE_dossier_user = new HashSet<DO_DOSUTE_dossier_user>();
        }
    
        public int DO_DOSSIE_ID { get; set; }
        public string DO_DOSSIE_CODE { get; set; }
        public string DO_DOSSIE_DESCRIPTION { get; set; }
        public Nullable<int> DO_DOSSIE_CLADOS_ID { get; set; }
        public Nullable<int> DO_Magic_BusinessObjectType_ID { get; set; }
        public bool DO_DOSSIE_FLAG_ACTIVE { get; set; }
        public bool DO_DOSSIE_FL_PRIVAT { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual DO_CLADOS_dossier_class DO_CLADOS_dossier_class { get; set; }
        public virtual ICollection<DO_DOSTIP_dosssier_type_document> DO_DOSTIP_dosssier_type_document { get; set; }
        public virtual Magic_BusinessObjectTypes Magic_BusinessObjectTypes { get; set; }
        public virtual ICollection<DO_DOSUTE_dossier_user> DO_DOSUTE_dossier_user { get; set; }
    }
}
