//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_DOCFIL_document_file
    {
        public DO_DOCFIL_document_file()
        {
            this.DO_DOCVER_versions1 = new HashSet<DO_DOCVER_versions>();
        }
    
        public int DO_DOCFIL_ID { get; set; }
        public int DO_DOCFIL_DO_DOCUME_ID { get; set; }
        public string DO_DOCFIL_NOTE { get; set; }
        public System.DateTime DO_DOCFIL_DATE { get; set; }
        public int DO_DOCFIL_USERID { get; set; }
        public Nullable<int> DO_DOCFIL_DO_DOCVER_LAST { get; set; }
        public Nullable<bool> DO_DOCFIL_FLAG_MAIN_ASSET { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual DO_DOCVER_versions DO_DOCVER_versions { get; set; }
        public virtual ICollection<DO_DOCVER_versions> DO_DOCVER_versions1 { get; set; }
        public virtual DO_DOCUME_documents DO_DOCUME_documents { get; set; }
    }
}
