//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_DOCVER_versions
    {
        public DO_DOCVER_versions()
        {
            this.DO_DOCFIL_document_file = new HashSet<DO_DOCFIL_document_file>();
        }
    
        public int DO_DOCVER_ID { get; set; }
        public int DO_DOCVER_DO_DOCFIL_ID { get; set; }
        public int DO_DOCVER_COUNTER { get; set; }
        public string DO_DOCVER_NOTE { get; set; }
        public System.DateTime DO_DOCVER_DATE { get; set; }
        public int DO_DOCVER_USERID { get; set; }
        public string DO_DOCVER_LINK_FILE { get; set; }
        public string DO_DOCVER_THUMBNAIL_LINK { get; set; }
        public Nullable<bool> DO_DOCVER_FLAG_AGGIORNATO { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<DO_DOCFIL_document_file> DO_DOCFIL_document_file { get; set; }
        public virtual DO_DOCFIL_document_file DO_DOCFIL_document_file1 { get; set; }
    }
}
