//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_OBTIDO_type_document
    {
        public int DO_OBTIDO_ID { get; set; }
        public Nullable<int> DO_OBTIDO_DO_TIPDOC_ID { get; set; }
        public Nullable<int> DO_OBTIDO_BusinessObjectType_ID { get; set; }
        public string DO_OBTIDO_VIEW_MISSING { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual DO_TIPDOC_document_type DO_TIPDOC_document_type { get; set; }
        public virtual Magic_BusinessObjectTypes Magic_BusinessObjectTypes { get; set; }
    }
}
