//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_STADOC_status
    {
        public DO_STADOC_status()
        {
            this.DO_CLASTA_class_status = new HashSet<DO_CLASTA_class_status>();
            this.DO_STAWRK_status_workflow = new HashSet<DO_STAWRK_status_workflow>();
            this.DO_DOCUME_documents = new HashSet<DO_DOCUME_documents>();
            this.DO_TIPDOC_document_type = new HashSet<DO_TIPDOC_document_type>();
        }
    
        public int DO_STADOC_ID { get; set; }
        public string DO_STADOC_CODE { get; set; }
        public string DO_STADOC_DESCRIPTION { get; set; }
        public Nullable<bool> DO_STADOC_FLAG_HISTORY { get; set; }
        public Nullable<bool> DO_STADOC_FLAG_CAD { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public Nullable<bool> DO_STADOC_FLAG_START { get; set; }
    
        public virtual ICollection<DO_CLASTA_class_status> DO_CLASTA_class_status { get; set; }
        public virtual ICollection<DO_STAWRK_status_workflow> DO_STAWRK_status_workflow { get; set; }
        public virtual ICollection<DO_DOCUME_documents> DO_DOCUME_documents { get; set; }
        public virtual ICollection<DO_TIPDOC_document_type> DO_TIPDOC_document_type { get; set; }
    }
}
