//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_STAWRK_status_workflow
    {
        public int DO_STAWRK_ID { get; set; }
        public int DO_STAWKR_DO_STADOC_ID { get; set; }
        public int DO_STAWRK_WrkStatus_Id { get; set; }
        public int DO_STAWRK_WrkTypeAct_id { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual DO_STADOC_status DO_STADOC_status { get; set; }
    }
}
