//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_TIPDOC_document_type
    {
        public DO_TIPDOC_document_type()
        {
            this.DO_DOSTIP_dosssier_type_document = new HashSet<DO_DOSTIP_dosssier_type_document>();
            this.DO_OBTIDO_type_document = new HashSet<DO_OBTIDO_type_document>();
            this.DO_CAMUSE_fields_document_user = new HashSet<DO_CAMUSE_fields_document_user>();
            this.DO_DOCFIE_fields_document = new HashSet<DO_DOCFIE_fields_document>();
            this.DO_DOCUME_documents = new HashSet<DO_DOCUME_documents>();
            this.FL_TIPFIL_type_file = new HashSet<FL_TIPFIL_type_file>();
        }
    
        public int DO_TIPDOC_ID { get; set; }
        public int DO_TIPDOC_DO_CLADOC_ID { get; set; }
        public string DO_TIPDOC_CODE { get; set; }
        public string DO_TIPDOC_DESCRIPTION { get; set; }
        public bool DO_TIPDOC_FILE_MANDATORY { get; set; }
        public bool DO_TIPDOC_FLAG_MANDATORY_EXP { get; set; }
        public int DO_TIPDOC_DAY_MONITOR { get; set; }
        public string DO_TIPDOC_PATH { get; set; }
        public string DO_TIPDOC_EXTENSIONS { get; set; }
        public Nullable<int> MagicBOLayer_ID { get; set; }
        public bool DO_TIPDOC_FILE_MONITOR { get; set; }
        public Nullable<System.Guid> guidIdentifier { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public int DO_TIPDOC_DAY_MONITOR_DUE { get; set; }
        public Nullable<int> DO_TIPDOC_DO_STADOC_ID { get; set; }
    
        public virtual ICollection<DO_DOSTIP_dosssier_type_document> DO_DOSTIP_dosssier_type_document { get; set; }
        public virtual ICollection<DO_OBTIDO_type_document> DO_OBTIDO_type_document { get; set; }
        public virtual DO_CLADOC_document_class DO_CLADOC_document_class { get; set; }
        public virtual ICollection<DO_CAMUSE_fields_document_user> DO_CAMUSE_fields_document_user { get; set; }
        public virtual ICollection<DO_DOCFIE_fields_document> DO_DOCFIE_fields_document { get; set; }
        public virtual ICollection<DO_DOCUME_documents> DO_DOCUME_documents { get; set; }
        public virtual DO_STADOC_status DO_STADOC_status { get; set; }
        public virtual ICollection<FL_TIPFIL_type_file> FL_TIPFIL_type_file { get; set; }
    }
}
