//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_V_DOCUME_MISSING
    {
        public int DO_CLADOC_ID { get; set; }
        public string DO_CLADOC_CODE { get; set; }
        public string DO_CLADOC_DESCRIPTION { get; set; }
        public string DO_CLADOC_PATH { get; set; }
        public int DO_TIPDOC_ID { get; set; }
        public string DO_TIPDOC_CODE { get; set; }
        public string DO_TIPDOC_DESCRIPTION { get; set; }
        public string DO_TIPDOC_EXTENSIONS { get; set; }
        public string DO_TIPDOC_PATH { get; set; }
        public int MagicBOLayerID { get; set; }
        public string OBJECT_DESCRIPTION { get; set; }
        public string OBJECT_CODE { get; set; }
        public string OBJECT_ID { get; set; }
    }
}
