//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_V_DOCUME_ENTITY
    {
        public int DO_DOCUME_ID { get; set; }
        public int DO_DOCUME_DO_TIPDOC_ID { get; set; }
        public string DO_DOCUME_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_EXPIRY_DATE { get; set; }
        public int DO_DOCUME_DO_STADOC_ID { get; set; }
        public bool DO_DOCUME_FLAG_NO_ACTIVE { get; set; }
        public string DO_DOCUME_XML_CAMASS_VALUES { get; set; }
        public string DO_DOCUME_XML_CAMUTE_VALUES { get; set; }
        public int DO_TIPDOC_DO_CLADOC_ID { get; set; }
        public string DO_TIPDOC_EXTENSIONS { get; set; }
        public string DO_TIPDOC_PATH { get; set; }
        public string DO_CLADOC_PATH { get; set; }
        public string DO_STADOC_DESCRIPTION { get; set; }
        public Nullable<int> MagicBOLayerID { get; set; }
        public string fakeforlink { get; set; }
        public string DO_CLADOC_DESCRIPTION { get; set; }
        public string DO_TIPDOC_DESCRIPTION { get; set; }
        public Nullable<int> DO_DOCREL_ID_RECORD { get; set; }
        public string DO_DOCREL_TABLE_NAME { get; set; }
        public Nullable<System.DateTime> DO_DOCUME_DATA_PROT { get; set; }
        public string DO_DOCUME_NUM_PROT { get; set; }
        public string DO_DOCUME_NOTE { get; set; }
        public string DO_DOCUME_NUM { get; set; }
        public string DO_DOCUME_CODE { get; set; }
        public Nullable<int> DO_DOCUME_ID_PADRE { get; set; }
        public Nullable<bool> DO_CLADOC_FLAG_PHOTO { get; set; }
        public string DO_DOCUME_FLAG_FATHER { get; set; }
        public string GROUPS_LIST { get; set; }
        public bool DO_DOCUME_FL_PRIVAT { get; set; }
    }
}
