//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_V_DOCVER
    {
        public int DO_DOCVER_ID { get; set; }
        public int DO_DOCVER_DO_DOCFIL_ID { get; set; }
        public int DO_DOCVER_COUNTER { get; set; }
        public string DO_DOCVER_NOTE { get; set; }
        public System.DateTime DO_DOCVER_DATE { get; set; }
        public int DO_DOCVER_USERID { get; set; }
        public string DO_DOCVER_LINK_FILE { get; set; }
        public string USERNAME { get; set; }
        public int DO_DOCFIL_DO_DOCUME_ID { get; set; }
    }
}
