//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DO_V_DOCFIE_class_doc_fields
    {
        public int DO_DOCFIE_ID { get; set; }
        public Nullable<int> DO_DOCFIE_DO_CLADOC_ID { get; set; }
        public Nullable<int> DO_DOCFIE_DO_TIPDOC_ID { get; set; }
        public Nullable<bool> DO_DOCFIE_MANDATORY { get; set; }
        public string DO_DOCFIE_FIELD_DB { get; set; }
        public string DO_DOCFIE_TABLE_JOIN { get; set; }
        public string DO_DOCFIE_FIELD_JOIN { get; set; }
        public string DO_DOCFIE_DESCRIPTION_JOIN { get; set; }
        public int DO_DOCFIE_MagicColumnID { get; set; }
        public Nullable<int> DO_DOCFIE_CF_FIELDS_DATA_TYPE_ID { get; set; }
        public int DO_DOCFIE_TAB_NAME { get; set; }
        public Nullable<int> DO_DOCFIE_ORDINAL_POSITION { get; set; }
        public string Columns_label { get; set; }
        public int MagicGrid_ID { get; set; }
        public string MagicGridName { get; set; }
    }
}
