//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EV_EVENT_EVENTS
    {
        public int EV_EVENT_ID { get; set; }
        public int EV_EVENT_EV_RULCAT_ID { get; set; }
        public Nullable<int> EV_EVENT_EV_STAGE_ID { get; set; }
        public string EV_EVENT_MSTR_KEY_NAME { get; set; }
        public Nullable<int> EV_EVENT_MSTR_KEY_VALUE { get; set; }
        public string EV_EVENT_CHLD_KEY_NAME { get; set; }
        public Nullable<int> EV_EVENT_CHLD_KEY_VALUE { get; set; }
        public System.DateTime EV_EVENT_DATE { get; set; }
        public int EV_EVENT_USER_ID { get; set; }
        public bool EV_EVENT_B_NO_VSBL { get; set; }
        public string EV_EVENT_CUSTOM_MSG { get; set; }
    }
}
