//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_FILINP_input_file
    {
        public int FL_FILINP_ID { get; set; }
        public int FL_FILINP_FL_TIPFIL_ID { get; set; }
        public int FL_FILINP_ORDER { get; set; }
        public string FL_FILINP_COLUMN_NAME { get; set; }
        public Nullable<bool> FL_FILINP_MANDATORY { get; set; }
        public int FL_FILINP_EX_EXCTIP_ID { get; set; }
        public string FL_FILINP_TABLE_JOIN { get; set; }
        public string FL_FILINP_FIELD_JOIN { get; set; }
        public string FL_FILINP_DESCRIPTION_JOIN { get; set; }
        public Nullable<bool> FL_FILINP_FLAG_VISIBILITY { get; set; }
        public Nullable<bool> FL_FILINP_FLAG_LIST { get; set; }
        public string FL_FILINP_CONDITION_VALID { get; set; }
        public Nullable<int> FL_FILINP_DATAROLE_ID { get; set; }
        public string FL_FILINP_FIELD_DB_FOR_UPDATE { get; set; }
    
        public virtual EX_EXCTIP_type_excel EX_EXCTIP_type_excel { get; set; }
        public virtual FL_TIPFIL_type_file FL_TIPFIL_type_file { get; set; }
    }
}
