//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_FORMAT_format
    {
        public FL_FORMAT_format()
        {
            this.FL_RECFIL_fields = new HashSet<FL_RECFIL_fields>();
        }
    
        public int FL_FORMAT_ID { get; set; }
        public string FL_FORMAT_CODE { get; set; }
        public string FL_FORMAT_DESCRIPTION { get; set; }
        public string FL_FORMAT_PATTERN { get; set; }
    
        public virtual ICollection<FL_RECFIL_fields> FL_RECFIL_fields { get; set; }
    }
}
