//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_RECFIL_fields
    {
        public int FL_RECFIL_ID { get; set; }
        public int FL_RECFIL_FL_TIPFIL_ID { get; set; }
        public int FL_RECFIL_NR_FIELD { get; set; }
        public string FL_RECFIL_DESCRIPTION { get; set; }
        public string FL_RECFIL_FIELD_NAME_EXCT { get; set; }
        public Nullable<int> FL_RECFIL_LENGHT { get; set; }
        public Nullable<int> FL_RECFIL_FL_FORMAT_ID { get; set; }
        public Nullable<int> FL_RECFIL_EX_EXCTIP_ID { get; set; }
        public bool FL_RECFIL_ALLOW_NULL { get; set; }
        public string FL_RECFIL_DEFAULT { get; set; }
        public string FL_RECFIL_NAME_HEADER { get; set; }
        public bool FL_RECFIL_FILLER { get; set; }
        public string FL_RECFIL_VALUE_ALLOWED { get; set; }
        public string FL_RECFIL_TABLE_JOIN { get; set; }
        public string FL_RECFIL_FIELD_JOIN { get; set; }
    
        public virtual EX_EXCTIP_type_excel EX_EXCTIP_type_excel { get; set; }
        public virtual FL_TIPFIL_type_file FL_TIPFIL_type_file { get; set; }
        public virtual FL_FORMAT_format FL_FORMAT_format { get; set; }
    }
}
