//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_TIPFIL_type_file
    {
        public FL_TIPFIL_type_file()
        {
            this.FL_FILINP_input_file = new HashSet<FL_FILINP_input_file>();
            this.FL_RECFIL_fields = new HashSet<FL_RECFIL_fields>();
        }
    
        public int FL_TIPFIL_ID { get; set; }
        public int FL_TIPFIL_FL_CLAFIL_ID { get; set; }
        public string FL_TIPFIL_CODE { get; set; }
        public string FL_TIPFIL_DESCRIPTION { get; set; }
        public bool FL_TIPFIL_FLAG_HEADING { get; set; }
        public string FL_TIPFIL_DELIMITER { get; set; }
        public bool FL_TIPFIL_LENGH_FIX { get; set; }
        public Nullable<int> FL_TIPFIL_LENGHT_RECORD { get; set; }
        public bool FL_TIPFIL_OUTPUT { get; set; }
        public string FL_TIPFIL_SP_EXEC { get; set; }
        public string FL_TIPFIL_EXTENSION { get; set; }
        public string FL_TIPFIL_SITO_FTP { get; set; }
        public Nullable<int> FL_TIPFIL_DO_TIPDOC_ID { get; set; }
        public string FL_TIPFIL_FILE_NAME { get; set; }
    
        public virtual DO_TIPDOC_document_type DO_TIPDOC_document_type { get; set; }
        public virtual FL_CLAFIL_class_file FL_CLAFIL_class_file { get; set; }
        public virtual ICollection<FL_FILINP_input_file> FL_FILINP_input_file { get; set; }
        public virtual ICollection<FL_RECFIL_fields> FL_RECFIL_fields { get; set; }
    }
}
