//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_ANAPRO_jobana_proare
    {
        public int JO_ANAPRO_ID { get; set; }
        public Nullable<int> JO_ANAPRO_JO_JOBANA_ID { get; set; }
        public Nullable<int> JO_ANAPRO_JO_PROARE_ID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual JO_JOBANA_job_steps JO_JOBANA_job_steps { get; set; }
    }
}
