//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_ACTIVE_JOBS
    {
        public int JO_JOBEVE_ID { get; set; }
        public Nullable<System.DateTime> JO_JOBEVE_END_DATE { get; set; }
        public int JO_JOBEVE_JO_TIPJOB_ID { get; set; }
        public int US_AREVIS_ID { get; set; }
    }
}
