//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_EXEORD_execution_order
    {
        public JO_EXEORD_execution_order()
        {
            this.JO_JOBANA_job_steps = new HashSet<JO_JOBANA_job_steps>();
            this.JO_JOBFIE_job_fields = new HashSet<JO_JOBFIE_job_fields>();
        }
    
        public int JO_EXEORD_ID { get; set; }
        public int JO_EXEORD_JO_STAJOB_ID { get; set; }
        public int JO_EXEORD_JO_TIPJOB_ID { get; set; }
        public int JO_EXEORD_ORDINE { get; set; }
        public string JO_EXEORD_STORED { get; set; }
        public string JO_EXEORD_STORED_UNDO { get; set; }
        public Nullable<bool> JO_EXEORD_FLAG_END { get; set; }
        public string JO_EXEORD_VIEW_POST { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<JO_JOBANA_job_steps> JO_JOBANA_job_steps { get; set; }
        public virtual ICollection<JO_JOBFIE_job_fields> JO_JOBFIE_job_fields { get; set; }
    }
}
