//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_JOBGRO_Job_groups
    {
        public int JO_JOBGRO_ID { get; set; }
        public int JO_JOBGRO_JO_JOBEVE_ID { get; set; }
        public int JO_JOBGRO_US_GROUPS_ID { get; set; }
        public Nullable<int> JO_JOBGRO_US_AREVIS_ID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual JO_JOBEVE_jobs JO_JOBEVE_jobs { get; set; }
        public virtual US_GROUPS_groups US_GROUPS_groups { get; set; }
        public virtual US_AREVIS_area_visibility US_AREVIS_area_visibility { get; set; }
    }
}
