//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_JOBINP_job_input
    {
        public int JO_JOBINP_ID { get; set; }
        public int JO_JOBINP_JO_JOBANA_ID { get; set; }
        public int JO_JOBINP_JO_JOBFIE_ID { get; set; }
        public string JO_JOBINP_VALUE { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual JO_JOBANA_job_steps JO_JOBANA_job_steps { get; set; }
        public virtual JO_JOBFIE_job_fields JO_JOBFIE_job_fields { get; set; }
    }
}
