//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_JOBEVE_jobs
    {
        public JO_JOBEVE_jobs()
        {
            this.JO_JOBANA_job_steps = new HashSet<JO_JOBANA_job_steps>();
            this.JO_JOBGRO_Job_groups = new HashSet<JO_JOBGRO_Job_groups>();
        }
    
        public int JO_JOBEVE_ID { get; set; }
        public int JO_JOBEVE_JO_TIPJOB_ID { get; set; }
        public int JO_JOBEVE_JO_LAST_EXEORD_ID { get; set; }
        public Nullable<System.DateTime> JO_JOBEVE_START_DATE { get; set; }
        public Nullable<System.DateTime> JO_JOBEVE_END_DATE { get; set; }
        public string JO_JOBEVE_NOTE { get; set; }
        public int JO_JOBEVE_USER_ID { get; set; }
        public Nullable<int> JO_JOBEVE_TASKID { get; set; }
        public Nullable<System.DateTime> JO_JOBEVE_CANCELLATION_DATE { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<JO_JOBANA_job_steps> JO_JOBANA_job_steps { get; set; }
        public virtual ICollection<JO_JOBGRO_Job_groups> JO_JOBGRO_Job_groups { get; set; }
    }
}
