//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_JOBNOT_notification
    {
        public int JO_JOBNOT_ID { get; set; }
        public int JO_JOBNOT_JO_JOBANA_ID { get; set; }
        public string JO_JOBNOT_NOTIFICATION1 { get; set; }
        public Nullable<System.DateTime> JO_JOBNOT_DATE_NOTIFICATION { get; set; }
        public Nullable<System.DateTime> JO_JOBNOT_DATE { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual JO_JOBANA_job_steps JO_JOBANA_job_steps { get; set; }
    }
}
