//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_JOBREC_job_record
    {
        public long JO_JOBREC_ID { get; set; }
        public int JO_JOBREC_JO_JOBANA_ID { get; set; }
        public string JO_JOBREC_TABLE_NAME { get; set; }
        public int JO_JOBREC_ID_RECORD { get; set; }
        public bool JO_JOBREC_SELECTED { get; set; }
        public Nullable<System.DateTime> JO_JOBREC_DATE { get; set; }
        public Nullable<int> JO_JOBRED_USERID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual JO_JOBANA_job_steps JO_JOBANA_job_steps { get; set; }
    }
}
