//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JO_JOBFIE_job_fields
    {
        public JO_JOBFIE_job_fields()
        {
            this.JO_JOBINP_job_input = new HashSet<JO_JOBINP_job_input>();
        }
    
        public int JO_JOBFIE_ID { get; set; }
        public int JO_JOBFIE_JO_EXEORD_ID { get; set; }
        public int JO_JOBFIE_ORDER { get; set; }
        public string JO_JOBFIE_COLUMN_NAME { get; set; }
        public string JO_JOBFIE_COLUMN_TYPE { get; set; }
        public Nullable<bool> JO_JOBFIE_MANDATORY { get; set; }
        public string JO_JOBFIE_COLUMN_TABLE_JOIN { get; set; }
        public string JO_JOBFIE_DESCRIPT_TABLE_JOIN { get; set; }
        public Nullable<bool> JO_JOBFIE_FLAG_USER_TABLE_JOIN { get; set; }
        public string JO_JOBFIE_COLUMN_FATHER { get; set; }
        public string JO_JOBFIE_COLUMN_JOIN_FATHER { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public Nullable<int> JO_JOBFIE_DATAROLE_ID { get; set; }
        public string JO_JOBFIE_TABLE_JOIN { get; set; }
    
        public virtual JO_EXEORD_execution_order JO_EXEORD_execution_order { get; set; }
        public virtual ICollection<JO_JOBINP_job_input> JO_JOBINP_job_input { get; set; }
    }
}
