//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TIPSAS_TIPASS
    {
        public Nullable<long> viewID { get; set; }
        public int AS_TIPASS_ID { get; set; }
        public string AS_TIPASS_CODE { get; set; }
        public string AS_TIPASS_DESCRIPTION { get; set; }
        public int AS_TIPSAS_ID { get; set; }
        public string AS_TIPSAS_CODICE { get; set; }
        public string AS_TIPSAS_DESCRIZIONE { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<int> AS_SUBTIP_ORDINE { get; set; }
    }
}
