//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RefTreeEntities : DbContext
    {
        public RefTreeEntities()
            : base("name=RefTreeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JO_JOBANA_job_steps> JO_JOBANA_job_steps { get; set; }
        public virtual DbSet<JO_JOBEVE_jobs> JO_JOBEVE_jobs { get; set; }
        public virtual DbSet<JO_JOBFIE_job_fields> JO_JOBFIE_job_fields { get; set; }
        public virtual DbSet<STREET_V_streetExtended> STREET_V_streetExtended { get; set; }
        public virtual DbSet<AS_SUBTIP_asset_subtipo> AS_SUBTIP_asset_subtipo { get; set; }
        public virtual DbSet<JO_EXEORD_execution_order> JO_EXEORD_execution_order { get; set; }
        public virtual DbSet<JO_JOBINP_job_input> JO_JOBINP_job_input { get; set; }
        public virtual DbSet<JO_JOBNOT_notification> JO_JOBNOT_notification { get; set; }
        public virtual DbSet<US_AREGRO_area_groups> US_AREGRO_area_groups { get; set; }
        public virtual DbSet<US_GROUPS_groups> US_GROUPS_groups { get; set; }
        public virtual DbSet<JO_JOBREC_job_record> JO_JOBREC_job_record { get; set; }
        public virtual DbSet<JO_ACTIVE_JOBS> JO_ACTIVE_JOBS { get; set; }
        public virtual DbSet<JO_JOBGRO_Job_groups> JO_JOBGRO_Job_groups { get; set; }
        public virtual DbSet<JO_ANAPRO_jobana_proare> JO_ANAPRO_jobana_proare { get; set; }
        public virtual DbSet<US_AREVIS_area_visibility> US_AREVIS_area_visibility { get; set; }
        public virtual DbSet<DO_CLAUTE_class_document_user> DO_CLAUTE_class_document_user { get; set; }
        public virtual DbSet<DO_DOCREL_document_relation> DO_DOCREL_document_relation { get; set; }
        public virtual DbSet<DO_STADOC_status> DO_STADOC_status { get; set; }
        public virtual DbSet<EV_EVENT_EVENTS> EV_EVENT_EVENTS { get; set; }
        public virtual DbSet<DO_CLASTA_class_status> DO_CLASTA_class_status { get; set; }
        public virtual DbSet<DO_TIPDOC_document_type> DO_TIPDOC_document_type { get; set; }
        public virtual DbSet<DO_DOCFIL_document_file> DO_DOCFIL_document_file { get; set; }
        public virtual DbSet<DO_DOCVER_versions> DO_DOCVER_versions { get; set; }
        public virtual DbSet<CF_FIELDS_DATA_TYPE> CF_FIELDS_DATA_TYPE { get; set; }
        public virtual DbSet<DO_V_DOCVER> DO_V_DOCVER { get; set; }
        public virtual DbSet<WF_V_ACTAGG_aggregate_activities> WF_V_ACTAGG_aggregate_activities { get; set; }
        public virtual DbSet<DO_DOSSIE_dossier> DO_DOSSIE_dossier { get; set; }
        public virtual DbSet<DO_CLADOS_dossier_class> DO_CLADOS_dossier_class { get; set; }
        public virtual DbSet<DO_DOCGRO_Document_groups> DO_DOCGRO_Document_groups { get; set; }
        public virtual DbSet<DO_DOSTIP_dosssier_type_document> DO_DOSTIP_dosssier_type_document { get; set; }
        public virtual DbSet<DO_OBTIDO_type_document> DO_OBTIDO_type_document { get; set; }
        public virtual DbSet<DO_STAWRK_status_workflow> DO_STAWRK_status_workflow { get; set; }
        public virtual DbSet<DO_CLADOC_document_class> DO_CLADOC_document_class { get; set; }
        public virtual DbSet<DO_V_DOCUME_MISSING> DO_V_DOCUME_MISSING { get; set; }
        public virtual DbSet<M_TIPSAS_TIPASS> M_TIPSAS_TIPASS { get; set; }
        public virtual DbSet<DO_CAMUSE_fields_document_user> DO_CAMUSE_fields_document_user { get; set; }
        public virtual DbSet<DO_DOCFIE_fields_document> DO_DOCFIE_fields_document { get; set; }
        public virtual DbSet<AS_V_LOCATION_locationextended> AS_V_LOCATION_locationextended { get; set; }
        public virtual DbSet<Magic_BusinessObjectTypes> Magic_BusinessObjectTypes { get; set; }
        public virtual DbSet<DO_V_DOCFIE_class_doc_fields> DO_V_DOCFIE_class_doc_fields { get; set; }
        public virtual DbSet<AS_ASSET_asset> AS_ASSET_asset { get; set; }
        public virtual DbSet<DO_DOCUME_documents> DO_DOCUME_documents { get; set; }
        public virtual DbSet<DO_V_DOCFIL> DO_V_DOCFIL { get; set; }
        public virtual DbSet<DO_V_DOCUME_ENTITY> DO_V_DOCUME_ENTITY { get; set; }
        public virtual DbSet<DO_V_DOCUME> DO_V_DOCUME { get; set; }
        public virtual DbSet<DO_DOSUTE_dossier_user> DO_DOSUTE_dossier_user { get; set; }
        public virtual DbSet<US_AREGRI_Arepro_Grids> US_AREGRI_Arepro_Grids { get; set; }
        public virtual DbSet<US_AREFUN__Arepro_Functions> US_AREFUN__Arepro_Functions { get; set; }
        public virtual DbSet<WF_V_ACTCAL_activities_calendar> WF_V_ACTCAL_activities_calendar { get; set; }
        public virtual DbSet<AS_V_ASSET_assetExtended> AS_V_ASSET_assetExtended { get; set; }
        public virtual DbSet<EX_EXCTIP_type_excel> EX_EXCTIP_type_excel { get; set; }
        public virtual DbSet<FL_CLAFIL_class_file> FL_CLAFIL_class_file { get; set; }
        public virtual DbSet<FL_FILINP_input_file> FL_FILINP_input_file { get; set; }
        public virtual DbSet<FL_TIPFIL_type_file> FL_TIPFIL_type_file { get; set; }
        public virtual DbSet<FL_RECFIL_fields> FL_RECFIL_fields { get; set; }
        public virtual DbSet<FL_FORMAT_format> FL_FORMAT_format { get; set; }
    
        public virtual ObjectResult<string> GET_TIPSAS_DETAILTOHIDE(Nullable<int> tipsas_id)
        {
            var tipsas_idParameter = tipsas_id.HasValue ?
                new ObjectParameter("tipsas_id", tipsas_id) :
                new ObjectParameter("tipsas_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GET_TIPSAS_DETAILTOHIDE", tipsas_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetAllowedTipSasFromParent(Nullable<int> tipsasparent_id)
        {
            var tipsasparent_idParameter = tipsasparent_id.HasValue ?
                new ObjectParameter("tipsasparent_id", tipsasparent_id) :
                new ObjectParameter("tipsasparent_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetAllowedTipSasFromParent", tipsasparent_idParameter);
        }
    
        public virtual int JO_JOBNOT_setasnotified(Nullable<int> notificationid)
        {
            var notificationidParameter = notificationid.HasValue ?
                new ObjectParameter("notificationid", notificationid) :
                new ObjectParameter("notificationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("JO_JOBNOT_setasnotified", notificationidParameter);
        }
    
        public virtual ObjectResult<JO_GET_UI_ELEMENTS_Result> JO_GET_UI_ELEMENTS(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JO_GET_UI_ELEMENTS_Result>("JO_GET_UI_ELEMENTS", user_idParameter);
        }
    
        public virtual ObjectResult<EV_GET_FUNCTIONS_FOR_STATUS_Result> EV_GET_FUNCTIONS_FOR_STATUS(string table_name, string id_record)
        {
            var table_nameParameter = table_name != null ?
                new ObjectParameter("table_name", table_name) :
                new ObjectParameter("table_name", typeof(string));
    
            var id_recordParameter = id_record != null ?
                new ObjectParameter("id_record", id_record) :
                new ObjectParameter("id_record", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EV_GET_FUNCTIONS_FOR_STATUS_Result>("EV_GET_FUNCTIONS_FOR_STATUS", table_nameParameter, id_recordParameter);
        }
    
        public virtual ObjectResult<usp_do_fascicolo_GetList_Result> usp_do_fascicolo_GetList(string xmlInput)
        {
            var xmlInputParameter = xmlInput != null ?
                new ObjectParameter("xmlInput", xmlInput) :
                new ObjectParameter("xmlInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_do_fascicolo_GetList_Result>("usp_do_fascicolo_GetList", xmlInputParameter);
        }
    
        public virtual ObjectResult<usp_do_fascicolo_GetDocuments_Result> usp_do_fascicolo_GetDocuments(string xmlInput, ObjectParameter count)
        {
            var xmlInputParameter = xmlInput != null ?
                new ObjectParameter("xmlInput", xmlInput) :
                new ObjectParameter("xmlInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_do_fascicolo_GetDocuments_Result>("usp_do_fascicolo_GetDocuments", xmlInputParameter, count);
        }
    
        public virtual ObjectResult<get_do_cladoc_for_user_Result> get_do_cladoc_for_user(string xmlInput, ObjectParameter count)
        {
            var xmlInputParameter = xmlInput != null ?
                new ObjectParameter("xmlInput", xmlInput) :
                new ObjectParameter("xmlInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_do_cladoc_for_user_Result>("get_do_cladoc_for_user", xmlInputParameter, count);
        }
    
        public virtual ObjectResult<usp_do_dossier_GetMissingDocs_Result> usp_do_dossier_GetMissingDocs(string xmlInput, ObjectParameter count)
        {
            var xmlInputParameter = xmlInput != null ?
                new ObjectParameter("xmlInput", xmlInput) :
                new ObjectParameter("xmlInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_do_dossier_GetMissingDocs_Result>("usp_do_dossier_GetMissingDocs", xmlInputParameter, count);
        }
    
        public virtual ObjectResult<usp_do_botypes_GetList_Result> usp_do_botypes_GetList(string xmlInput)
        {
            var xmlInputParameter = xmlInput != null ?
                new ObjectParameter("xmlInput", xmlInput) :
                new ObjectParameter("xmlInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_do_botypes_GetList_Result>("usp_do_botypes_GetList", xmlInputParameter);
        }
    
        public virtual ObjectResult<GET_ASSET_TREE_Result> GET_ASSET_TREE(Nullable<int> aS_ASSET_ID)
        {
            var aS_ASSET_IDParameter = aS_ASSET_ID.HasValue ?
                new ObjectParameter("AS_ASSET_ID", aS_ASSET_ID) :
                new ObjectParameter("AS_ASSET_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_ASSET_TREE_Result>("GET_ASSET_TREE", aS_ASSET_IDParameter);
        }
    
        [DbFunction("RefTreeEntities", "AS_GET_ASSET_MAIN_TB")]
        public virtual IQueryable<AS_GET_ASSET_MAIN_TB_Result> AS_GET_ASSET_MAIN_TB(Nullable<int> as_asset_id)
        {
            var as_asset_idParameter = as_asset_id.HasValue ?
                new ObjectParameter("As_asset_id", as_asset_id) :
                new ObjectParameter("As_asset_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AS_GET_ASSET_MAIN_TB_Result>("[RefTreeEntities].[AS_GET_ASSET_MAIN_TB](@As_asset_id)", as_asset_idParameter);
        }
    
        public virtual ObjectResult<DO_GET_UI_ELEMENTS_Result> DO_GET_UI_ELEMENTS(Nullable<int> user_id, Nullable<int> arevis_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var arevis_idParameter = arevis_id.HasValue ?
                new ObjectParameter("arevis_id", arevis_id) :
                new ObjectParameter("arevis_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DO_GET_UI_ELEMENTS_Result>("DO_GET_UI_ELEMENTS", user_idParameter, arevis_idParameter);
        }
    
        public virtual ObjectResult<DO_SP_DOCUMENTS_L_Result> DO_SP_DOCUMENTS_L(string xmlinput, ObjectParameter count)
        {
            var xmlinputParameter = xmlinput != null ?
                new ObjectParameter("xmlinput", xmlinput) :
                new ObjectParameter("xmlinput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DO_SP_DOCUMENTS_L_Result>("DO_SP_DOCUMENTS_L", xmlinputParameter, count);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_Getgroupsfromarevis(Nullable<int> uSERID, Nullable<int> aREVISID)
        {
            var uSERIDParameter = uSERID.HasValue ?
                new ObjectParameter("USERID", uSERID) :
                new ObjectParameter("USERID", typeof(int));
    
            var aREVISIDParameter = aREVISID.HasValue ?
                new ObjectParameter("AREVISID", aREVISID) :
                new ObjectParameter("AREVISID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_Getgroupsfromarevis", uSERIDParameter, aREVISIDParameter);
        }
    
        public virtual ObjectResult<PP_GET_UI_ELEMENTS_Result> PP_GET_UI_ELEMENTS(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PP_GET_UI_ELEMENTS_Result>("PP_GET_UI_ELEMENTS", user_idParameter);
        }
    
        public virtual ObjectResult<GetWaterMarkForUser_Result> GetWaterMarkForUser(Nullable<int> idUser, Nullable<int> ugvi)
        {
            var idUserParameter = idUser.HasValue ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(int));
    
            var ugviParameter = ugvi.HasValue ?
                new ObjectParameter("ugvi", ugvi) :
                new ObjectParameter("ugvi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWaterMarkForUser_Result>("GetWaterMarkForUser", idUserParameter, ugviParameter);
        }
    
        [DbFunction("RefTreeEntities", "utf_us_aregrid_cross")]
        public virtual IQueryable<utf_us_aregrid_cross_Result> utf_us_aregrid_cross(string magicgridname, Nullable<int> magicgridid)
        {
            var magicgridnameParameter = magicgridname != null ?
                new ObjectParameter("magicgridname", magicgridname) :
                new ObjectParameter("magicgridname", typeof(string));
    
            var magicgrididParameter = magicgridid.HasValue ?
                new ObjectParameter("magicgridid", magicgridid) :
                new ObjectParameter("magicgridid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utf_us_aregrid_cross_Result>("[RefTreeEntities].[utf_us_aregrid_cross](@magicgridname, @magicgridid)", magicgridnameParameter, magicgrididParameter);
        }
    
        [DbFunction("RefTreeEntities", "utf_us_arefun_cross")]
        public virtual IQueryable<utf_us_arefun_cross_Result> utf_us_arefun_cross(Nullable<int> functionid, Nullable<System.Guid> functionguid)
        {
            var functionidParameter = functionid.HasValue ?
                new ObjectParameter("functionid", functionid) :
                new ObjectParameter("functionid", typeof(int));
    
            var functionguidParameter = functionguid.HasValue ?
                new ObjectParameter("functionguid", functionguid) :
                new ObjectParameter("functionguid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utf_us_arefun_cross_Result>("[RefTreeEntities].[utf_us_arefun_cross](@functionid, @functionguid)", functionidParameter, functionguidParameter);
        }
    
        [DbFunction("RefTreeEntities", "utf_AS_V_ASSET_assetgroups")]
        public virtual IQueryable<utf_AS_V_ASSET_assetgroups_Result> utf_AS_V_ASSET_assetgroups(Nullable<int> iAssetId, Nullable<int> iArevisId)
        {
            var iAssetIdParameter = iAssetId.HasValue ?
                new ObjectParameter("iAssetId", iAssetId) :
                new ObjectParameter("iAssetId", typeof(int));
    
            var iArevisIdParameter = iArevisId.HasValue ?
                new ObjectParameter("iArevisId", iArevisId) :
                new ObjectParameter("iArevisId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utf_AS_V_ASSET_assetgroups_Result>("[RefTreeEntities].[utf_AS_V_ASSET_assetgroups](@iAssetId, @iArevisId)", iAssetIdParameter, iArevisIdParameter);
        }
    
        [DbFunction("RefTreeEntities", "utf_US_V_GROUPS_groupsassets")]
        public virtual IQueryable<utf_US_V_GROUPS_groupsassets_Result> utf_US_V_GROUPS_groupsassets(Nullable<int> iGroupId)
        {
            var iGroupIdParameter = iGroupId.HasValue ?
                new ObjectParameter("iGroupId", iGroupId) :
                new ObjectParameter("iGroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<utf_US_V_GROUPS_groupsassets_Result>("[RefTreeEntities].[utf_US_V_GROUPS_groupsassets](@iGroupId)", iGroupIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetAllowedTipSasForAsset(Nullable<int> asset_id)
        {
            var asset_idParameter = asset_id.HasValue ?
                new ObjectParameter("asset_id", asset_id) :
                new ObjectParameter("asset_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetAllowedTipSasForAsset", asset_idParameter);
        }
    
        public virtual int cl_sp_ctr_field_event(string schema, string table_name, string key, string field_key, Nullable<int> cultureId, Nullable<int> ev_stage_id, ObjectParameter text_err)
        {
            var schemaParameter = schema != null ?
                new ObjectParameter("Schema", schema) :
                new ObjectParameter("Schema", typeof(string));
    
            var table_nameParameter = table_name != null ?
                new ObjectParameter("table_name", table_name) :
                new ObjectParameter("table_name", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            var field_keyParameter = field_key != null ?
                new ObjectParameter("Field_key", field_key) :
                new ObjectParameter("Field_key", typeof(string));
    
            var cultureIdParameter = cultureId.HasValue ?
                new ObjectParameter("CultureId", cultureId) :
                new ObjectParameter("CultureId", typeof(int));
    
            var ev_stage_idParameter = ev_stage_id.HasValue ?
                new ObjectParameter("Ev_stage_id", ev_stage_id) :
                new ObjectParameter("Ev_stage_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cl_sp_ctr_field_event", schemaParameter, table_nameParameter, keyParameter, field_keyParameter, cultureIdParameter, ev_stage_idParameter, text_err);
        }
    }
}
