//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_AREVIS_area_visibility
    {
        public US_AREVIS_area_visibility()
        {
            this.JO_JOBGRO_Job_groups = new HashSet<JO_JOBGRO_Job_groups>();
            this.US_AREGRO_area_groups = new HashSet<US_AREGRO_area_groups>();
        }
    
        public int US_AREVIS_ID { get; set; }
        public int US_AREVIS_US_CLAVIS_ID { get; set; }
        public string US_AREVIS_DESCRIPTION { get; set; }
        public Nullable<int> US_AREVIS_PARENT_ID { get; set; }
        public Nullable<int> US_AREVIS_GROUP_TO_SEARCH { get; set; }
        public Nullable<int> US_AREVIS_ORDER { get; set; }
        public string US_AREVIS_LOGO { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual ICollection<JO_JOBGRO_Job_groups> JO_JOBGRO_Job_groups { get; set; }
        public virtual ICollection<US_AREGRO_area_groups> US_AREGRO_area_groups { get; set; }
        public virtual US_GROUPS_groups US_GROUPS_groups { get; set; }
    }
}
