//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_AREGRO_area_groups
    {
        public int US_AREGRO_ID { get; set; }
        public int US_AREGRO_US_AREVIS_ID { get; set; }
        public Nullable<int> US_AREGRO_US_GROUPS_ID { get; set; }
        public Nullable<int> US_AREGRO_LE_AMMGRO_ID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
    
        public virtual US_GROUPS_groups US_GROUPS_groups { get; set; }
        public virtual US_AREVIS_area_visibility US_AREVIS_area_visibility { get; set; }
    }
}
