//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_AREGRI_Arepro_Grids
    {
        public int US_AREGRI_ID { get; set; }
        public Nullable<int> US_AREGRI_US_PROARE_ID { get; set; }
        public Nullable<int> US_AREGRI_MagicGridID { get; set; }
        public string MagicGridName { get; set; }
        public Nullable<System.Guid> GridGUID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public Nullable<System.Guid> guidIdentifier { get; set; }
    }
}
