//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_AREFUN__Arepro_Functions
    {
        public int US_AREFUN_ID { get; set; }
        public Nullable<int> US_AREFUN_US_PROARE_ID { get; set; }
        public Nullable<int> US_AREFUN_FunctionID { get; set; }
        public Nullable<System.Guid> FunctionGUID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public Nullable<System.Guid> guidIdentifier { get; set; }
    }
}
