//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class US_GROUPS_groups
    {
        public US_GROUPS_groups()
        {
            this.US_AREGRO_area_groups = new HashSet<US_AREGRO_area_groups>();
            this.JO_JOBGRO_Job_groups = new HashSet<JO_JOBGRO_Job_groups>();
            this.US_AREVIS_area_visibility = new HashSet<US_AREVIS_area_visibility>();
            this.DO_CLAUTE_class_document_user = new HashSet<DO_CLAUTE_class_document_user>();
            this.DO_DOCGRO_Document_groups = new HashSet<DO_DOCGRO_Document_groups>();
            this.DO_DOSUTE_dossier_user = new HashSet<DO_DOSUTE_dossier_user>();
        }
    
        public int US_GROUPS_ID { get; set; }
        public int US_GROUPS_US_TIPGRU_ID { get; set; }
        public string US_GROUPS_DESCRIPTION { get; set; }
        public System.DateTime US_GROUPS_FROM { get; set; }
        public Nullable<System.DateTime> US_GROUPS_TO { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> cUserId { get; set; }
        public string US_GROUPS_CODE { get; set; }
    
        public virtual ICollection<US_AREGRO_area_groups> US_AREGRO_area_groups { get; set; }
        public virtual ICollection<JO_JOBGRO_Job_groups> JO_JOBGRO_Job_groups { get; set; }
        public virtual ICollection<US_AREVIS_area_visibility> US_AREVIS_area_visibility { get; set; }
        public virtual ICollection<DO_CLAUTE_class_document_user> DO_CLAUTE_class_document_user { get; set; }
        public virtual ICollection<DO_DOCGRO_Document_groups> DO_DOCGRO_Document_groups { get; set; }
        public virtual ICollection<DO_DOSUTE_dossier_user> DO_DOSUTE_dossier_user { get; set; }
    }
}
