//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_V_ACTAGG_aggregate_activities
    {
        public int taskTypeID { get; set; }
        public string Color { get; set; }
        public Nullable<int> LinkedModelActivity_ID { get; set; }
        public string Activity { get; set; }
        public System.DateTime start { get; set; }
        public Nullable<int> ownerId { get; set; }
        public string ActivitySource { get; set; }
        public Nullable<int> US_DEPROL_ID { get; set; }
        public Nullable<int> US_USEROL_ID { get; set; }
        public string US_USEROL_DESCRIPTION { get; set; }
        public Nullable<int> US_DEPART_ID { get; set; }
        public string US_DEPART_DESCRIPTION { get; set; }
        public Nullable<int> MandatoryAssignment { get; set; }
        public int ToBeAssigned { get; set; }
        public Nullable<int> Activity_counter { get; set; }
        public string taskTypeDescription { get; set; }
    }
}
