//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ref3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_V_ACTCAL_activities_calendar
    {
        public int taskId { get; set; }
        public System.DateTime start { get; set; }
        public Nullable<int> taskTypeID { get; set; }
        public Nullable<int> LinkedModelActivity_ID { get; set; }
        public Nullable<int> ownerId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ProcessFunction_ID { get; set; }
        public string ACT_BO_ID { get; set; }
        public Nullable<int> ACT_BO_Type_ID { get; set; }
        public Nullable<int> ActivityInstance_ID { get; set; }
        public string WF_BO_ID { get; set; }
        public Nullable<int> WF_BO_Type_ID { get; set; }
        public int RequiresCheckList { get; set; }
        public int RequiresDocUpload { get; set; }
        public int MandatoryAssignment { get; set; }
        public bool GenerateBO { get; set; }
        public Nullable<int> actionid { get; set; }
        public string actiontype { get; set; }
        public string actioncommand { get; set; }
        public string actionfilter { get; set; }
        public Nullable<System.Guid> FunctionGUID { get; set; }
        public string PrecOutStatus { get; set; }
        public string PrecActivityType { get; set; }
        public string Note { get; set; }
        public string UploadedFile { get; set; }
    }
}
