//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_MailQueue
    {
        public int id { get; set; }
        public Nullable<int> system_messages_id { get; set; }
        public Nullable<int> edited_messages_id { get; set; }
        public string taglist { get; set; }
        public Nullable<int> mail_account_id { get; set; }
        public string error_messages { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public int send_attempts { get; set; }
        public string note { get; set; }
        public int error_counter { get; set; }
        public Nullable<System.DateTime> send_time { get; set; }
        public Nullable<System.DateTime> last_attempt { get; set; }
        public string send_to { get; set; }
        public string reply_to { get; set; }
        public Nullable<bool> is_in_process { get; set; }
    
        public virtual Magic_MailAccounts Magic_MailAccounts { get; set; }
        public virtual Magic_SystemEditedMessages Magic_SystemEditedMessages { get; set; }
        public virtual Magic_SystemMessages Magic_SystemMessages { get; set; }
    }
}
