//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_SystemEditedMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magic_SystemEditedMessages()
        {
            this.Magic_MailQueue = new HashSet<Magic_MailQueue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrigMessage_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Code { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string cc { get; set; }
        public string ccn { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsHtml { get; set; }
        public Nullable<int> CultureId { get; set; }
        public string Attachments { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string BO_ID { get; set; }
        public string BOType { get; set; }
        public string attachJSON { get; set; }
    
        public virtual Magic_SystemMessages Magic_SystemMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magic_MailQueue> Magic_MailQueue { get; set; }
    }
}
