//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_MailAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magic_MailAccounts()
        {
            this.Magic_SystemMessages = new HashSet<Magic_SystemMessages>();
            this.Magic_MailQueue = new HashSet<Magic_MailQueue>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string email { get; set; }
        public string from_name { get; set; }
        public string password { get; set; }
        public int port { get; set; }
        public bool tls_or_ssl { get; set; }
        public string uri { get; set; }
        public bool IsDefault { get; set; }
        public bool is_pec { get; set; }
        public string smtp_account_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magic_SystemMessages> Magic_SystemMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magic_MailQueue> Magic_MailQueue { get; set; }
    }
}
