//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_NotificationQueue
    {
        public int id { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<int> user_id { get; set; }
        public int notificationType_ID { get; set; }
        public bool notified { get; set; }
        public Nullable<System.DateTime> notified_at { get; set; }
        public int send_attempts { get; set; }
        public Nullable<System.DateTime> last_attempt { get; set; }
        public string message { get; set; }
        public string error { get; set; }
        public Nullable<int> provider_ID { get; set; }
        public string mobile { get; set; }
        public string notes { get; set; }
        public bool readByUser { get; set; }
        public Nullable<int> DocumentRepository_ID { get; set; }
        public string function_link { get; set; }
        public string function_filter { get; set; }
        public bool can_reply { get; set; }
        public Nullable<int> sender_user_id { get; set; }
        public bool display_modal_unread { get; set; }
    
        public virtual Magic_NotificationProviders Magic_NotificationProviders { get; set; }
        public virtual Magic_NotificationTypes Magic_NotificationTypes { get; set; }
    }
}
