//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_Mmb_PendingRegistrations
    {
        public long ID { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public string password { get; set; }
        public System.DateTime created_at { get; set; }
        public bool completed_registration { get; set; }
    }
}
