//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_SystemMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magic_SystemMessages()
        {
            this.Magic_SystemEditedMessages = new HashSet<Magic_SystemEditedMessages>();
            this.Magic_MailQueue = new HashSet<Magic_MailQueue>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string cc { get; set; }
        public string ccn { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsHtml { get; set; }
        public Nullable<int> CultureId { get; set; }
        public string Attachments { get; set; }
        public Nullable<int> MailAccounts_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magic_SystemEditedMessages> Magic_SystemEditedMessages { get; set; }
        public virtual Magic_MailAccounts Magic_MailAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magic_MailQueue> Magic_MailQueue { get; set; }
    }
}
