//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magic_NotificationProviders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magic_NotificationProviders()
        {
            this.Magic_NotificationQueue = new HashSet<Magic_NotificationQueue>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Server_url { get; set; }
        public string Credential_user { get; set; }
        public string Credential_pwd { get; set; }
        public string License_key { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magic_NotificationQueue> Magic_NotificationQueue { get; set; }
    }
}
