//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicFramework.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MagicDBEntities : DbContext
    {
        public MagicDBEntities()
            : base("name=MagicDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Magic_Mmb_PendingRegistrations> Magic_Mmb_PendingRegistrations { get; set; }
        public virtual DbSet<Magic_SystemEditedMessages> Magic_SystemEditedMessages { get; set; }
        public virtual DbSet<Magic_SystemMessages> Magic_SystemMessages { get; set; }
        public virtual DbSet<Magic_NotificationProviders> Magic_NotificationProviders { get; set; }
        public virtual DbSet<Magic_NotificationQueue> Magic_NotificationQueue { get; set; }
        public virtual DbSet<Magic_NotificationTypes> Magic_NotificationTypes { get; set; }
        public virtual DbSet<Magic_MailAccounts> Magic_MailAccounts { get; set; }
        public virtual DbSet<Magic_MailQueue> Magic_MailQueue { get; set; }
        public virtual DbSet<V_Magic_NotificationQueue> V_Magic_NotificationQueue { get; set; }
    
        public virtual int Magic_Mmb_UserRegistration(string xmlInput, ObjectParameter registered, ObjectParameter message)
        {
            var xmlInputParameter = xmlInput != null ?
                new ObjectParameter("xmlInput", xmlInput) :
                new ObjectParameter("xmlInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Magic_Mmb_UserRegistration", xmlInputParameter, registered, message);
        }
    }
}
