//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Login", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail inviata. Controlla la tua mailbox per resettare la password.
        /// </summary>
        internal static string checkMails {
            get {
                return ResourceManager.GetString("checkMails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail inviata. Controlla la tua mail per confermare l&apos;iscrizione.
        /// </summary>
        internal static string checkYourMail {
            get {
                return ResourceManager.GetString("checkYourMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prego contattare il reparto tecnico.
        /// </summary>
        internal static string contactAdmin {
            get {
                return ResourceManager.GetString("contactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password dimenticata?.
        /// </summary>
        internal static string forgotPw {
            get {
                return ResourceManager.GetString("forgotPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessun problema, clicca qui per recuperare la password.
        /// </summary>
        internal static string forgotPwRecover {
            get {
                return ResourceManager.GetString("forgotPwRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel login!.
        /// </summary>
        internal static string loginFailed {
            get {
                return ResourceManager.GetString("loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accedi.
        /// </summary>
        internal static string loginTitle {
            get {
                return ResourceManager.GetString("loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accedi tramite.
        /// </summary>
        internal static string loginWith {
            get {
                return ResourceManager.GetString("loginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo utente?.
        /// </summary>
        internal static string newAccount {
            get {
                return ResourceManager.GetString("newAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualora l&apos;utenza risulti attiva nel portale, riceverà a breve una mail  per reimpostarla.
        /// </summary>
        internal static string pwdrec {
            get {
                return ResourceManager.GetString("pwdrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricordami.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessione scaduta.
        /// </summary>
        internal static string sesexp {
            get {
                return ResourceManager.GetString("sesexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invio.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo user è stato bloccato.
        /// </summary>
        internal static string Thesupplieduserislockedout {
            get {
                return ResourceManager.GetString("Thesupplieduserislockedout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provare più tardi, grazie.
        /// </summary>
        internal static string tooManyPasswordChangesPerHour {
            get {
                return ResourceManager.GetString("tooManyPasswordChangesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems while changing password.
        /// </summary>
        internal static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
    }
}
