using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace MagicFramework.Helpers
{
    public class PythonHandler
    {
        //path to the python.exe executable
        public string pythonExecutable { get; set; }
        //command line args, the first is the script name. Space is the separation char.
        public string args { get; set; }

          
        public PythonHandler(string pythonExecutable, string args)
        {
            this.pythonExecutable = pythonExecutable;
            this.args = args;
        }
        /// <summary>
        /// Runs a python script synchronously throwing an error if the python script fails. The output is a string containing the standard output (e.g. print "test") result
        /// </summary>
        public string ExecuteSynch()
        {
            string result = String.Empty;
            string stderr = String.Empty;
            try
            {
                ProcessStartInfo start = new ProcessStartInfo();
                start.FileName = this.pythonExecutable;//cmd is full path to python.exe
                start.Arguments = this.args;//args is path to .py file and any cmd line args
                start.UseShellExecute = false;// Do not use OS shell
                start.CreateNoWindow = true; // We don't need new window
                start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
                start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)


                
                using (Process process = Process.Start(start))
                {
                    using (StreamReader reader = process.StandardOutput)
                    {
                          stderr = process.StandardError.ReadToEnd(); // Here are te exceptions from our Python script
                          result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    }
                }
            }
            catch (Exception ex) {
                throw new System.ArgumentException(ex.Message);
            }
            if (!String.IsNullOrEmpty(stderr))
                throw new System.ArgumentException(stderr);
            return result;

        }


        public Process ExecuteAsynch(string logFile, string runningPythonScript,string executionContext,Action<string,string> outputManager)
        {
            var processStartInfo = new ProcessStartInfo(this.pythonExecutable,this.args)
            {
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true
            };



            string result = String.Empty;
            string stderr = String.Empty;
            var process = new Process { StartInfo = processStartInfo, EnableRaisingEvents = true };

            MFLog.LogInFile(runningPythonScript + " is going to be started", MFLog.logtypes.INFO, logFile);
            //process.Exited += (s, ea) => onSuccess(this.output_path);
            //                             MFLog.LogInFile(runningPythonScript + " ends",MFLog.logtypes.INFO,logFile);
            process.OutputDataReceived += (s, ea) => 
            outputManager(ea.Data, executionContext); 
                           //                         Console.WriteLine(ea.Data);
     
            process.ErrorDataReceived += (s, ea) => MFLog.LogInFile(runningPythonScript + " : " + ea.Data, MFLog.logtypes.ERROR, logFile);

            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
            return process;
        }
    }
}